### ISSUE TITLE
Unable to dump ACNH update 2.0.0.0

### ISSUE THREAD

**Issue by MichaelHinrichs** [DarkMatterCore/nxdumptool#100]
I'm attempting to dump update 2.0.0.0 of Animal Crossing New Horizons, but the "use update/DLC" option only has "No" for the base game, update 0.1.6.0, and DLC 0.0.0.0. I am running NXDumpTool 1.1.14, and have update 2.0.0.0 installed on my switch. What's going on?

I want update 2.0.0.0 to appear in "use update/DLC"

This may be something that i'm doing wrong, instead on nxdupmtool's fault, but any help i can be given will be appreciated.

**Comment by DarkMatterCore** [comment]
The version numbers displayed by the title selectors don't reflect the version numbers displayed by Horizon OS when you push the + button on a game. These version numbers are stored in the NACP from games and updates, and extracting/parsing this data isn't implemented in legacy nxdumptool.

Update 0.1.6.0 most likely is what you're looking for.

**Comment by MichaelHinrichs** [comment]
Apparently it was. It went to a different folder than my previous dumps from a few months back.
