### ISSUE TITLE
Error when trying to dump pokemon brilliant pokemon + 4gb update

### ISSUE THREAD

**Issue by Machow8** [DarkMatterCore/nxdumptool#101]
**Describe the bug**
When i go to dump pokemon brilliant diamond base game and it's latest 4gb update data via 'RomFS section data dump', it shows the following error: "parseBktrEntryFromNca: invalid NCA BKTR subsection header size!".

**To Reproduce**

Choose Dump installed SD card / eMMC content > Choose Pokémon Brilliant Diamond > RomFS options > Set 'Use update/DLC' as 'yes:0100000011D90900 v131072 (UPD) (SD Card)' and click on 'RomFS section data dump' > Error appears

**Please fill the following information:**
- Horizon OS (Switch FW) version: EmuMMC on 13.1.0;
- CFW: Atmosphere;
- CFW version: 1.2.3;
- Atmosphère launch method (if applicable): fusee-primary;
- NXDumpTool version: 1.1.14;
- Homebrew launch method: title override (homebrew channel installed as NSP);
- Source storage used with the application (if applicable): SD/eMMC;
- SD card specs: Samsung EVO 256 GB, EXFAT partition;

**Screenshots**
https://i.imgur.com/AaEopQp.png

**Additional context**
None.

**Comment by duljab** [comment]
I am having the same issue as well. 

**To Reproduce:**

Choose Dump gamecard content > Choose Pokémon Brilliant Diamond > RomFS options > Set 'Use update/DLC' as 'yes:0100000011D90900 v131072 (0.0.2.0) (UPD) (SD Card)' and click on 'RomFS section data dump' > Error appears immediately

**Please fill the following information:**

    Horizon OS (Switch FW) version: SysMMC on 13.1.0;
    CFW: Atmosphere;
    CFW version: 1.2.3;
    Atmosphère launch method (if applicable): Hekate;
    NXDumpTool version: 1.1.14;
    Homebrew launch method: title override (homebrew channel installed as NSP);
    Source storage used with the application (if applicable): SD/;
    SD card specs: Samsung pro endurance 128 GB, EXFAT partition;

**Screenshots:**

![2021112621233300-9C8D9BB5A41F26A6FDE24068CFF8EAF9](https://user-images.githubusercontent.com/35856679/143665390-86e070a7-95df-45b2-b8b1-1eb99bf9fd03.jpg)

**Comment by duljab** [comment]
Updating my Keys with the most recent release of Lockpick_RCM fixed this issue for me. I can now dump my RomFS.

**Comment by Machow8** [comment]
> Updating my Keys with the most recent release of Lockpick_RCM fixed this issue for me. I can now dump my RomFS.

I also dumped keys from EmuMMC 13.1.0 and now it's working again!

Thx for that!
