### ISSUE TITLE
Error: parseRomFsEntryFromNca: invalid header size for NCA RomFS section!

### ISSUE THREAD

**Issue by thisiscb31** [DarkMatterCore/nxdumptool#103]
I keep getting this error when I try to dump "no more heroes 3"
![thumbnail](https://user-images.githubusercontent.com/97644415/149245495-d3eab36b-590c-4f37-bd5f-398a94237bf1.jpeg)

**Comment by INCHINS** [comment]
Same thing happens to me while trying to dump or even view the RomFS for Tetris 99 and/or Pac-Man 99

**Comment by MrVtR** [comment]
Same error here with Chrono Cross The Radical Dreamers Edition

**Comment by aaronlink127** [comment]
I'm pretty sure dumping your keys with Lockpick RCM will fix the issue.

**Comment by DarkMatterCore** [comment]
Please refer to https://github.com/DarkMatterCore/nxdumptool/issues/104#issuecomment-1175102727. I'll close this issue.
