### ISSUE TITLE
NXDumpTool v1.1.15 Warning: missing keys

### ISSUE THREAD

**Issue by Jelle10324** [DarkMatterCore/nxdumptool#113]
Hello When i open nxdumptool i get on the bottom of my screen a warning that says
Warning: missing keys file at *sdmc:/switch/prod.keys*.
This file is needed to deal with the encryption schemes used by nintendo switch content files
SD/eMMC operations will be entirely disabled. along with NSP/ExeFS/RomFS related operations
please run lockpick_RCM to generate this file.

I open NXdumptool 
i see dump gamecard content 
dumo installed sd card / emmc content
update options

Warning: missing keys file at *sdmc:/switch/prod.keys*.
This file is needed to deal with the encryption schemes used by nintendo switch content files
SD/eMMC operations will be entirely disabled. along with NSP/ExeFS/RomFS related operations
please run lockpick_RCM to generate this file.

- nxdumptool v1.1.15
- Homebrew launch method applet
- SD/eMMC]
- FAT32 partition

i dont know what i'm doing i just want to download games to play with my family so can you please tell everything that i have to do.

**Comment by DarkMatterCore** [comment]
Hi there.

> please run lockpick_RCM to generate this file.

nxdumptool is telling you exactly what to do. Go download [Lockpick_RCM](https://github.com/shchmue/Lockpick_RCM) and dump your console keys, then run nxdumptool again.

**Comment by Jelle10324** [comment]
thanks for explaining it like that my english is really bad so when i read that i didnt know what to do appreciate it.

**Comment by DarkMatterCore** [comment]
> thanks for explaining it like that my english is really bad so when i read that i didnt know what to do appreciate it.

Don't worry, English isn't my mother tongue either. I'll close this issue.
