### ISSUE TITLE
Half of my Game cart dumps are corrupted. 

### ISSUE THREAD

**Issue by RyabDev** [DarkMatterCore/nxdumptool#114]
**Describe the bug**
After dumping all my game carts. Half of them are combining back into corrupted files. Tested by emulation and attempting to reinstall to system.
**To Reproduce**

**Please fill the following information:**
- Horizon OS (Switch FW) version: [e.g. 14.1.2]
- CFW: Atmosphere]
- CFW version: 1.3.2]
- Atmosphère launch method Hekate
- nxdumptool version: 1.1.15
- Homebrew launch method: Override
- Source storage used with the application SD
- SD card specs: [e.g. Sandisk 512gb, FAT32 partition]

**Screenshots**
![image](https://user-images.githubusercontent.com/16693525/180676046-77e93497-d5b2-483f-b729-81f74317ff5f.png)
When trying to run via emulator.

**Logfile**
If available, please upload your logfile located at `sdmc:/nxdumptool/nxdumptool.log`.
Cannot seem to locate or was deleted

**Comment by DarkMatterCore** [comment]
How are you exactly combining the generated part files? This doesn't seem right.

**Comment by RyabDev** [comment]
I used the latest build of NXDumpMerger. I double checked to see if it just corrupted during the merge but, it still gives save result after 2 merges.

**Comment by RyabDev** [comment]
After re-dumping them they seem to be find. Unsure what exactly happened though. These were dumped directly from cartridges.

**Comment by Dimensional** [comment]
If I may, it doesn't appear you would have needed to use NXDumpMerger. There is a guide on No-Intro that states you can use something that comes standard with your OS. [No-Intro Switch Card Dumping Guide - Merging Part Files](https://wiki.no-intro.org/index.php?title=Nintendo_Switch_Dumping_Guide#Merge_part_files_.28FAT32_only.29).

**Comment by Masamune3210** [comment]
All it is iirc is concatenating the parts back together, so "copy file1 + file2 + ....."on windows or the equivalent on Linux or macOS would probably be what you are looking for

**Comment by DarkMatterCore** [comment]
@RyabDev it was probably an issue within NXDumpMerger, from the looks of it. Glad to know you eventually got it to work, anyway.

I'll close this issue.
