### ISSUE TITLE
Invalid Directory/file Table for NCA Romf

### ISSUE THREAD

**Issue by Onii-133** [DarkMatterCore/nxdumptool#118]
Trying to dump romFS files for the game "Little Witch Nobeta" Results in the following error:
"Invalid Directory/file Table for NCA Romf"

I saw a previous issue (#39) having this same problem, however I was not able to find "debug.txt" in the sd root directory or "sdmc:/nxdumptool/nxdumptool.log"

Horizon Version 14.1.2
CFW - Atmosphere v1.3.2|E
Fusee-primary
nxdumptool version 15.0.0 - Using Override
Tried both Gamecard and installed eMMC

![image](https://user-images.githubusercontent.com/5142933/195386495-32dc2611-3a39-4a36-98a5-4aab51649de1.png)

**Comment by Masamune3210** [comment]
Try using the beta from the discord instead of the release version. It's quite far behind now last time I checked and doesn't handle any of the new stuff added since the last release

**Comment by Onii-133** [comment]
> Try using the beta from the discord instead of the release version. It's quite far behind now last time I checked and doesn't handle any of the new stuff added since the last release

oh i didn't realize there was a more up to date version on a discord server, i just have been using the in-app updater.
Will update if it fixes the problem

**Comment by DarkMatterCore** [comment]
Indeed, a lot of new stuff like proper BucketTree info/table management and support for other NCA storage types like Sparse and Compressed is only available in the rewrite branch's codebase.

I'm not willing to backport these changes -- I don't really want to touch legacy branch's codebase, not even with a 10ft pole.

I'll close this issue, but feel free to reopen it if needed.
