### ISSUE TITLE
Bayonetta 3 & Alan Wake Remastered romfs issues

### ISSUE THREAD

**Issue by Slluxx** [DarkMatterCore/nxdumptool#119]
**Describe the bug**
Alan Wake Remastered: `parseRomFsEntryFromNca: inavalid directory/file table for NCA RomFS section!`
Bayonetta 3: `parseRomFsEntryFromNca: invalid header size for NCA RomFs section (0x54B7310F9723F5AF at 0x0000000001BC4000)`

**To Reproduce**
Browse RomFS section on those games

**Please fill the following information:**
- Horizon OS (Switch FW) version: 15.0.1
- CFW: AMS
- CFW version: Latest
- Atmosphère launch method (if applicable): Hekate
- nxdumptool version: 1.1.15
- Homebrew launch method: override
- Source storage used with the application (if applicable): sd
- SD card specs: Samsung evo 512 fat32

**Screenshots**
unnessesary

**Logfile**
probably unnessesary

**Additional context**
na

**Comment by DarkMatterCore** [comment]
Use the rewrite builds from the Discord server, these problems won't be fixed in legacy builds as previously discussed in other issues. I'm only pushing code to the `rewrite` branch these days.

Feel free to reopen the issue if needed, though.

**Comment by Slluxx** [comment]
Knew that but didnt know if this issue is game specific and needs your attention for the next version.
What discord server btw?

**Comment by DarkMatterCore** [comment]
Nope, it's not game specific. Legacy nxdumptool is just lacking support for sparse and compression layers. NCA storage and Bucket Tree handling was rewritten from the ground up for `rewrite`.
