### ISSUE TITLE
Invalid directory/file....  #Front mission 1st

### ISSUE THREAD

**Issue by ThawidejC** [DarkMatterCore/nxdumptool#121]
Can't Dump Invalid #Front mission 1st 
it show : directory/file table for NCA RomFS section
![313790611_1218110919048108_8682857222937192197_n](https://user-images.githubusercontent.com/79046665/205431249-5228f40f-1e69-4a45-b437-75f80b8cc674.jpg)

**Comment by DarkMatterCore** [comment]
Use the `rewrite` builds from the Discord server, these problems won't be fixed in legacy builds as previously discussed in other issues. I'm only pushing code to the rewrite branch these days.

Feel free to reopen the issue if needed, though.
