### ISSUE TITLE
Consistent error while trying to dump Sonic Frontiers RomFS

### ISSUE THREAD

**Issue by claus296** [DarkMatterCore/nxdumptool#122]
![image](https://user-images.githubusercontent.com/81391522/205466277-61f1518e-a3ba-421d-bcaf-be3dbbf80871.jpg)

**Comment by DarkMatterCore** [comment]
Use the `rewrite` builds from the Discord server, these problems won't be fixed in legacy builds as previously discussed in other issues. I'm only pushing code to the rewrite branch these days.

Feel free to reopen the issue if needed, though.
