### ISSUE TITLE
NXDumpTool fails to dump XCI if the filename length exceeds 255chr

### ISSUE THREAD

**Issue by ToxiClay** [DarkMatterCore/nxdumptool#133]
**Describe the bug**
Attempting to dump a cartridge where the resulting filename would exceed 255chr fails outright; I expect because this exceeds filesystem limitations on file name length.

**To Reproduce**
1. Insert a game cartridge (in this case, the Atelier Mysterious Trilogy Deluxe Pack)
2. Initiate an XCI dump
3. Observe failure message

**Please fill the following information:**
- Horizon OS (Switch FW) version: [e.g. 16.0.2]
- CFW: Atmosphere
- CFW version: 1.5.2
- Atmosphère launch method (if applicable): Hekate, using package3
- nxdumptool version: 1.1.15
- Homebrew launch method: Album appled
- Source storage used with the application (if applicable): Gamecard
- SD card specs: Samsung Pro Plus 512GB, exFAT partition

**Screenshots**
![2023050320165400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/13796683/236078727-5eb14cd0-529a-4ece-a672-c2893ca500f5.jpg)

**Logfile**
No logfile was generated.

**Additional context**
I expect this will only be a problem in very particular edge cases; this card bundles six applications into one (the three games, and three digital art books), and NXDumpTool concatenates all bundled applications together to generate the file name.

**Comment by Masamune3210** [comment]
does this happen even with the rewrite? Filenames are enforced to be less than 255 chars by the filesystem itself, so the only way around this afaik would be to truncate the filename, or do what other programs like NSC_Builder do and just list the combo as #G+#U+#D, enumerating out the contents and filling in the numbers with how many of each are present

**Comment by ToxiClay** [comment]
Using the rewrite doesn't even get that far. Selecting "Start Dump" causes a small "test" message to appear in the upper right, but no other action is performed.

![2023050423321500-D7439E0E29A2308707D5F9909E9BB210](https://user-images.githubusercontent.com/13796683/236372376-29349d38-5858-42bd-864f-c5a43c52deb1.jpg)

Heading to "User Titles" to perform actions on the individual applications gives me the following screen, which I can't work out how to use.

![2023050423315800-D7439E0E29A2308707D5F9909E9BB210](https://user-images.githubusercontent.com/13796683/236372452-83335a53-7e9f-473a-b689-6393460d9d4b.jpg)

**Comment by ghost** [comment]
@ToxiClay You don't want to use the UI rewrite, as it's still very much a work in progress. You'll want to grab the `nxdumptool_rewrite_poc_2b8dcec.7z` from Artefacts and use the `gc_dumper` tool.

**Comment by DarkMatterCore** [comment]
As @KookiesGH mentioned, just use the [latest pre-release](https://github.com/DarkMatterCore/nxdumptool/releases/tag/rewrite-prerelease). I'll close this issue.
