### ISSUE TITLE
Failed To Read Header And 3072 Bytes Block

### ISSUE THREAD

**Issue by SuperKirbylover** [DarkMatterCore/nxdumptool#134]
tried to rip annalynn, and i got this error. is this something that i did or is this an issue with the game/nxdumptool?

![image](https://github.com/DarkMatterCore/nxdumptool/assets/37816816/f5a92557-8248-4e45-ad75-9cda1ebdfd7b)

**Comment by DarkMatterCore** [comment]
Error `0xA05` means `content not found`. If the game is stored in your SD card, you may want to double check its filesystem.

If you recently switched to a new SD card, you may also need to fix archive bit flags on subdirectories inside the `Nintendo` folder. You can do this using Hekate.

**Comment by SuperKirbylover** [comment]
how could i do it using hekate? sorry, i'm a bit new to hacking my switch ^^;

**Comment by Whovian9369** [comment]
> Error `0xA05` means `content not found`. If the game is stored in your SD card, you may want to double check its filesystem.
> 
> If you recently switched to a new SD card, you may also need to fix archive bit flags on subdirectories inside the `Nintendo` folder. You can do this using Hekate.

To add to this, you may also be dumping in emummc while the title's on your sysmmc, so you can also try (and we generally suggest to doing this) on your sysmmc,

**Comment by SuperKirbylover** [comment]
oh, i did try to dump while booted into sysmmc when i posted that screenshot!

**Comment by DarkMatterCore** [comment]
> how could i do it using hekate? sorry, i'm a bit new to hacking my switch ^^;

`Tools` -> `Arch bit • RCM • Touch • Pkg1/2` -> `Fix Archive Bit`

**Comment by SuperKirbylover** [comment]
this did it!! thank you :]

**Comment by DarkMatterCore** [comment]
Glad to help! In the future, please consider seeking support on our Discord server. There's a link for it in this project's README.
