### ISSUE TITLE
On firmware version 18.0.0, I cannot launch, "Error: No BFTTF Font retrieved "

### ISSUE THREAD

**Issue by bitelaserkhalif** [DarkMatterCore/nxdumptool#161]
**Describe the bug**
When I open up nxdumptool on version 18.0.0, an error shows up: "Error: No BFTTF Font retrieved ". Title and product key has been dumped. On version 17.0.1, it still work just fine

**To Reproduce**
1. Just launch NXdumpTool, and
2. Error: No BFTTF Font retrieved shows up, I cannot do anything except closing it.

**Please fill the following information:**
- Horizon OS (Switch FW) version: [e.g. 18.0.0] version 18.0.0 on Emunand
- CFW: [e.g. Atmosphère, SX OS, etc.] ATMOSPHERE
- CFW version: [e.g. 0.11.1, 2.9.4, etc.] 1.7.0
- Atmosphère launch method (if applicable): [e.g. Hekate, fusee-primary] Hekate
- nxdumptool version: [e.g. 2.0.0] 2.0.0-rewrite
- Homebrew launch method: [e.g. title override, applet] title override / takeover
- Source storage used with the application (if applicable): [e.g. gamecard, SD/eMMC] SD Card
- SD card specs: [e.g. Samsung EVO 256 GB, FAT32 partition] 128gb Lexar FAT32

**Screenshots**
![2024033115004200-A040C187AE842F172A58B77C9DC32FFB](https://github.com/DarkMatterCore/nxdumptool/assets/100983886/e010774f-c782-4af1-bc53-32edb0e1920a)

![2024033115013600-57B4628D2267231D57E0FC1078C0596D](https://github.com/DarkMatterCore/nxdumptool/assets/100983886/c9998b50-3c99-47c3-9bd4-f9cfff83425f)

**Logfile**
[nxdt_rw_poc.log](https://github.com/DarkMatterCore/nxdumptool/files/14814629/nxdt_rw_poc.log)

**Additional context**

**Comment by DarkMatterCore** [comment]
Update your keys. 18.0.0 updated the master key generation. You need to use a different Lockpick_RCM build (which we won't provide).
