### ISSUE TITLE
Error on bfttfInitialize

### ISSUE THREAD

**Issue by 72Zn** [DarkMatterCore/nxdumptool#162]
**Describe the bug**
Starting nxdt_rw_poc fails with the following error.

```
An error ocurred while initializing resources.
bfttfInitialize: No BFTTF fonts retrieved!
For more information, please check the logfile. Press any button to exit.
```

**To Reproduce**
1. Launch hbmenu by pressing 'R' and opening an installed game
2. Select `nxdt_rw_poc` and launch with 'A'
3. See error

**Please fill the following information:**
- Horizon OS (Switch FW) version: 18.0.0
- CFW: atmosphere
- CFW version: 1.7.0-prerelease-35d93a7c4+hbl-2.4.4+hbmenu-3.6.0
- Atmosphère launch method (if applicable): Hekate
- nxdumptool version: 2.0.0
- Homebrew launch method: title override
- Source storage used with the application (if applicable): SD (emuMMC)
- SD card specs: SanDisk Ultra 512GB, FAT32 partition

**Logfile**
[nxdt_rw_poc.log](https://github.com/DarkMatterCore/nxdumptool/files/14816434/nxdt_rw_poc.log)

**Additional context**

**Comment by DarkMatterCore** [comment]
Please check: https://github.com/DarkMatterCore/nxdumptool/issues/161#issuecomment-2028597030
