### ISSUE TITLE
Failed to initialize bfttf font

### ISSUE THREAD

**Issue by lando07** [DarkMatterCore/nxdumptool#164]
**Describe the bug**
I have no clue why this happened, its never been an error in the past and I can't find it on google.

**To Reproduce**
Open hbloader and open nxdumptool_rw_proc.nro

**Please fill the following information:**
- Horizon OS (18.0.1)
- CFW: Atmosphere
- CFW version: 1.7
- Atmosphère launch method (if applicable): fusee.bin
- nxdumptool version: v2.2.0 (rewrite-41d053d-dirty)
- Homebrew launch method: applet
- Source storage used with the application (if applicable): SD
- SD card specs: Samsung EVO 256 GB, exFat

**Screenshots**
![2024051311522800-DB1426D1DFD034027CECDE9C2DD914B8](https://github.com/DarkMatterCore/nxdumptool/assets/96402540/ea00fd5d-3b97-4f91-b852-91f59a5326a7)

**Logfile**
[nxdt_rw_poc.log](https://github.com/DarkMatterCore/nxdumptool/files/15297798/nxdt_rw_poc.log)

**Additional context**
I've redumped my keys and both ryujinx and the forbidden emulator are happy with them.

**Comment by DarkMatterCore** [comment]
Manually update your nxdumptool rewrite NRO to the latest version and redump your console keys using a newer Lockpick_RCM build (which we can't provide nor tell you where to get it).

**Comment by lando07** [comment]
Ok thanks!
