### ISSUE TITLE
File help

### ISSUE THREAD

**Issue by Moddedmyth** [DarkMatterCore/nxdumptool#166]
Hey, is there a way to get a "main" file I'm missing it for a mod.

**Comment by Whovian9369** [comment]
You dump the exefs via nxdumptool, though this isn't the place to ask questions like this.
In the future, we would appreciate it if you please join [the Discord server](https://discord.gg/SCbbcQx) or create [a new Discussion post](https://github.com/DarkMatterCore/nxdumptool/discussions) instead.
