### ISSUE TITLE
host not work (AMS 1.7.1/18.0.1)

### ISSUE THREAD

**Issue by sskyNS** [DarkMatterCore/nxdumptool#167]
**Describe the bug**

**To Reproduce**

**Please fill the following information:**
- Horizon OS (Switch FW) version: [e.g. 10.0.0]
- CFW: [e.g. Atmosphère, SX OS, etc.]
- CFW version: [e.g. 0.11.1, 2.9.4, etc.]
- Atmosphère launch method (if applicable): [e.g. Hekate, fusee-primary]
- nxdumptool version: [e.g. 2.0.0]
- Homebrew launch method: [e.g. title override, applet]
- Source storage used with the application (if applicable): [e.g. gamecard, SD/eMMC]
- SD card specs: [e.g. Samsung EVO 256 GB, FAT32 partition]

**Screenshots**
Add screenshots to help explain your problem.

**Logfile**
If available, please upload your logfile located at `sdmc:/nxdumptool/nxdumptool.log`.

**Additional context**

**Comment by Whovian9369** [comment]
Did not fill out the issue template or provide any information about the actual issue, so I'm closing this.
