### ISSUE TITLE
"eticket_rsa_kek_personalized" unavailable in prod.keys.

### ISSUE THREAD

**Issue by damongooseman** [DarkMatterCore/nxdumptool#168]
**Describe the bug**
Error message is displayed upon launch of the program

**To Reproduce**
1. hold "R" and launch a game tile
2. Click on nxdt_rw_poc
3. See error

**Please fill the following information:**
- Horizon OS (Switch FW) version: [e.g. 10.0.0]
- CFW: Atmosphère
- CFW version: [e.g. 0.11.1, 2.9.4, etc.]
- Atmosphère launch method (if applicable): Hekate
- nxdumptool version: pre-release
- Homebrew launch method: title override
- Source storage used with the application (if applicable): n/a
- SD card specs: sandisk gold 256gb

**Screenshots**
Add screenshots to help explain your problem.

**Logfile**
[2024-08-11 00:44:16.086467368] [INFO] /source/core/nxdt_utils.c|161|utilsInitializeResources -> nxdt_rw_poc v2.0.0 starting (rewrite-00497b5-dirty). Built on 2024-08-08 10:28:39 UTC.
[2024-08-11 00:44:16.086512296] [INFO] /source/core/nxdt_utils.c|163|utilsInitializeResources -> Horizon OS version: 18.1.0.
[2024-08-11 00:44:16.086799284] [INFO] /source/core/nxdt_utils.c|175|utilsInitializeResources -> Detected Atmosphère CFW.
[2024-08-11 00:44:16.086815560] [INFO] /source/core/nxdt_utils.c|178|utilsInitializeResources -> Exosphère API version info:
- Release version: 1.7.1.
- PKG1 key generation: 17 (0x12).
- Target firmware: 18.1.0.
[2024-08-11 00:44:16.087062508] [INFO] /source/core/nxdt_utils.c|198|utilsInitializeResources -> Running under retail Mariko unit without Terra flag in title override mode.
[2024-08-11 00:44:16.087084088] [INFO] /source/core/nxdt_utils.c|203|utilsInitializeResources -> Launch path: "sdmc:/switch/nxdt_rw_poc.nro".
[2024-08-11 00:44:16.094875664] [INFO] /source/core/keys.c|632|keysReadKeysFromFile -> Loaded 1 key(s) from "sdmc:/switch/prod.keys".
[2024-08-11 00:44:16.094899376] [ERROR] /source/core/keys.c|641|keysReadKeysFromFile -> "eticket_rsa_kek_personalized" unavailable in "sdmc:/switch/prod.keys"!
[2024-08-11 00:44:16.094934580] [DEBUG] /source/core/keys.c|180|keysLoadKeyset -> eTicket RSA device key dump:
(key dump data redacted)
[2024-08-11 00:44:16.094970772] [DEBUG] /source/core/keys.c|181|keysLoadKeyset -> NX keyset dump:
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000(redacted)0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2024-08-11 00:45:48.725264956] [INFO] /source/core/nxdt_utils.c|317|utilsCloseResources -> Shutting down...

**Additional context**
I have dumped my prod.keys file with the RCM lockpick and placed that file in the same directory.  I did verify that eticket_rsa_kek_personalized is not listed in that file.  eticket_rsa_kek is listed but that obviously is not the same thing.  Any help is greatly appreciated. I have been trying to dump a 4 in 1 game card and have had zero success doing so, the game just says that I need to install the update when I try to launch it.  Single game gamecards work just fine.

**Comment by DarkMatterCore** [comment]
Make sure you're using an up to date Lockpick_RCM build. Given the current state of affairs, we can't tell you where to get it.

**Comment by damongooseman** [comment]
Ok, i will do some searching and see what I can find. Thank you for the suggestion.  Out of curiosity, what are the "current state of affairs" you are referring to?

**Comment by DarkMatterCore** [comment]
> Out of curiosity, what are the "current state of affairs" you are referring to?

The Yuzu lawsuit.

**Comment by damongooseman** [comment]
ahhh i see.  Had not heard of that.  Well thanks for the direction, hopefully that will solve it if I can find it
