### ISSUE TITLE
master header canr find, s

### ISSUE THREAD

**Issue by Microzod** [DarkMatterCore/nxdumptool#171]
**Describe the bug**

**To Reproduce**

**Please fill the following information:**
- Horizon OS (Switch FW) version: [e.g. 10.0.0]
- CFW: [e.g. Atmosphère, SX OS, etc.]
- CFW version: [e.g. 0.11.1, 2.9.4, etc.]
- Atmosphère launch method (if applicable): [e.g. Hekate, fusee-primary]
- nxdumptool version: [e.g. 2.0.0]
- Homebrew launch method: [e.g. title override, applet]
- Source storage used with the application (if applicable): [e.g. gamecard, SD/eMMC]
- SD card specs: [e.g. Samsung EVO 256 GB, FAT32 partition]

**Screenshots**
Add screenshots to help explain your problem.

**Logfile**
If available, please upload your logfile located at `sdmc:/nxdumptool/nxdumptool.log`.

**Additional context**

**Comment by DarkMatterCore** [comment]
I'm sorry, what?

**Comment by DarkMatterCore** [comment]
@Microzod I'm closing this issue. Please provide any details about the actual problem you're facing if you want to reopen it.
