### ISSUE TITLE
ETA shows 19H erroneously

### ISSUE THREAD

**Issue by mafischer** [DarkMatterCore/nxdumptool#20]
It seems as though the hour field in the remaining time is hard coded to be 19.

Gamecards used: `JUST DANCE® 2019, The Legend of Zelda Breath of the Wild, V-Rally 4`
SD card: `SanDisk Ultra 400GB microSDXC UHS-I`
gcdumptool version: `1.0.8`
CFW: `AtlasNX Kosmos`
Switch firmware: `7.0.1`

![2019061319571900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/1082176/59477298-37532300-8e1a-11e9-9a8b-81407667efbc.jpg)
![2019061320045000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/1082176/59477313-43d77b80-8e1a-11e9-8c0e-a8515df1cf6f.jpg)
![2019061320143100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/1082176/59477312-43d77b80-8e1a-11e9-843b-e232d217ae4c.jpg)
![2019061320160300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/1082176/59477311-43d77b80-8e1a-11e9-874c-e01d6c214b58.jpg)

**Comment by DarkMatterCore** [comment]
Could you please provide more information about your current setup? Stuff like this would be useful to know:

* Gamecard used.
* SD card model/capacity/brand.
* gcdumptool version.
* CFW type/version.
* Switch FW version.
* A screenshot in which the problem can be seen.

**Comment by mafischer** [comment]
@DarkMatterCore please see updated issue.

**Comment by DarkMatterCore** [comment]
This has been fixed on v1.1.0. Please update and test again.

**Comment by mafischer** [comment]
Yes, it’s fixed in 1.1.0
