### ISSUE TITLE
Title/content indexes for SD/eMMC titles are not being properly calculated on NSP/ExeFS/RomFS dumping.

### ISSUE THREAD

**Issue by Maschell** [DarkMatterCore/nxdumptool#21]
Everytime I want to dump an update I get "listTitlesByType: title count mismatch in ncmContentMetaDatabaseListApplication". Dumping a DLC works fine.
Using the latest 1.1.1 of nxdumptool on a 8.1.0 console

**Comment by DarkMatterCore** [comment]
Please upload a screenshot of the problem containing the displayed filter code.

Also, please provide more information about your setup, like:

* CFW used.
* CFW version.
* SD card brand/model/capacity.
* Title storage source (gamecard or SD/eMMC).

**Comment by Maschell** [comment]
- atmosphere-0.9.1-master-241b8f46
- Samsung Evo Plus 128GB 
- SD/eMMC

<img width="640" alt="screenshot" src="https://user-images.githubusercontent.com/8582508/59931966-6b47cd00-9446-11e9-82df-fe74ece62612.png">

**Comment by DarkMatterCore** [comment]
I think I have located the problem, thanks for your input!

Could you please test this build? https://mega.nz/#!wEwWEApA!k0lIYYo3lfMM0b9Ds8KqM3NRhFwoMRxMobtiqLaQF9s

Thanks in advance.

**Comment by DuIslingr** [comment]
> I think I have located the problem, thanks for your input!
> 
> Could you please test this build? [mega.nz/#!wEwWEApA!k0lIYYo3lfMM0b9Ds8KqM3NRhFwoMRxMobtiqLaQF9s](https://mega.nz/#!wEwWEApA!k0lIYYo3lfMM0b9Ds8KqM3NRhFwoMRxMobtiqLaQF9s)
> 
> Thanks in advance.
SXOS 2.8
Firm 8.1
Prod.keys file exists
Sandisk 128GB (Exfat) 
EMMC
I tried this test build as I had the same issue trying to dump the base game.
Different error occurs now.

[http://www.mediafire.com/view/26fhij7a3uds2rf/2019062200592600-DB1426D1DFD034027CECDE9C2DD914B8.jpg](image)
[http://www.mediafire.com/view/h9t845aclb87hs4/2019062200590300-DB1426D1DFD034027CECDE9C2DD914B8.jpg](image)

**Comment by DarkMatterCore** [comment]
That's even worse. The `ncmContentMetaDatabaseGet()` call comes before the check that should be fixed in that build. Where's the title installed? Have you tried another CFW?

**Comment by DarkMatterCore** [comment]
@Maschell @DuIslingr Please disregard that last build and try this one instead: https://mega.nz/#!oRpwWQzB!8Kmtr2pib4DUycevbQnUPHKLnc3iH85mpWwDv_EhtF4

Thanks again.

**Comment by DarkMatterCore** [comment]
This is actually related to the fact that SD card titles and eMMC titles are collectively treated as an unique storage source, since the content retrieval methods used for both sources are identical. Title/content indexes were not being properly calculated.

**Comment by Maschell** [comment]
Ah, was it because we had titles on the eMMC AND SD card?

It does work now, thanks for the quick fix. (Althought by now I just used the switch built-in feature to update games on other switch consoles xD)

**Comment by DarkMatterCore** [comment]
@Maschell Yes, this was actually affecting more than just NSP dumping. Thanks for reporting this bug!

I wouldn't have noticed it otherwise since I only have SD card titles, and so did the other users that helped me with testing the previous version before releasing it.

I'm going to wait for @DuIslingr 's input on this matter. If it works for them, I'll close the issue.

**Comment by DuIslingr** [comment]
@DarkMatterCore I cant donwload the new file. its been removed? Was at work when you replied

**Comment by DarkMatterCore** [comment]
@DuIslingr Sorry, my bad. Here's the updated link: https://mega.nz/#!QBxVyAAY!synQBO0JPWe_GT5k0zIwYqSNKlXUrptQYZpfSokugMo

**Comment by DuIslingr** [comment]
Error is gone. Dumping now. This bug seems to be fixed.

**Comment by DarkMatterCore** [comment]
Thanks. I'm currently waiting for input from another user about a bug under FW 3.0.0 to push the changes. I'll close this issue as soon as that happens.

**Comment by staringstar** [comment]
The Download link is not working again. Can you upload it another time please?

**Comment by DarkMatterCore** [comment]
Fixed in 6d435a253293fcf49d386bcef654406e09a58360.

@staringstar Please check the new release.

**Comment by eruteru** [comment]
![error_message](https://github.com/DarkMatterCore/nxdumptool/assets/69401602/52159840-79ed-4f5c-8dc3-c41270c116cd)
It doesn't work for me either and I downloaded NXDumpTool this year.
Sometimes I also get a different Error Message. This time I only got the one mentioned above and this one:
![second error_message](https://github.com/DarkMatterCore/nxdumptool/assets/69401602/562e1dc1-597f-4604-b872-95b73563734a)

I followed this [guide](https://yuzu-emu.org/help/quickstart/) so I don't forget anything for this step.
