### ISSUE TITLE
Batch dumping of titles

### ISSUE THREAD

**Issue by Maschell** [DarkMatterCore/nxdumptool#22]
It would be great to have an option to batch-dump all titles on the SD/eMMC. Maybe with filter options (only SD, only eMMC, only Base, only DLC, only Updates)? With an option to skip or override existing titles.

Currently dumping all the contents it pretty annoying because you have to dump them individually. (+ there is no indication of which titles where already dumped)

**Comment by DarkMatterCore** [comment]
This is actually planned for the next release (well, the one after the bugfix I hope to release in a couple of hours).

X button will be used to enter batch mode.

**Comment by DarkMatterCore** [comment]
Fixed in a051b17ad070bc2cbd748de2eb7e712cb2562602.
