### ISSUE TITLE
Indicator if dumped version of the title already exist on the SD card.

### ISSUE THREAD

**Issue by Maschell** [DarkMatterCore/nxdumptool#24]
Similar to issue #23 and maybe #22 . It would be great to have some kind of indication of the list of titles on the SD/eMMC to show the user it already has been dumped (=> a file with the target filename exists on the sd card).

Context: Currently I am trying to dump all updates from my consoleand it's pretty hard to keep up with the updates I've already dumped.

**Comment by DarkMatterCore** [comment]
Fixed in 6d435a253293fcf49d386bcef654406e09a58360.
