### ISSUE TITLE
ncmContentStorageReadContentIdFile() fails with error 0x00017c05 under certain FW versions (gamecard only).

### ISSUE THREAD

**Issue by DarkMatterCore** [DarkMatterCore/nxdumptool#26]
Affects NSP/ExeFS/RomFS dumping. The user who reported this problem has a Switch console on 3.0.0. This seems to only affect gamecard NCA content retrieval.

Switchbrew states that this error occurs because the "gamecard is not initialized" (which, to be honest, got me perplexed).

I already tried a little bit of trickery, like reading a small data chunk from the gamecard using a IStorage instance, but nothing I came up with worked.

Fixing this without a proper correction would require rewriting NSP/ExeFS/RomFS dumping procedures to also work with a raw gamecard storage interface.

**Comment by Matt07211** [comment]
> Switchbrew states that this error occurs because the "gamecard is not initialized" (which, to be honest, got me perplexed).

I have encountered gamecard not initialized *once*, my switch had been asleep for a few days, woke it up and inserted a new switch card, and opened gcdumptool, it basically got stuck in a loop of the main screen with all the normal text and the line saying no game card inserted and a screen saying (if i remember correctly) please wait, it was looping so fast the text was alternating between the two at a pace that you would have trouble keeping up, I didn't report it as i was unable to reproduce that problem again, no idea if its the same problem you are describing but it popped into my head after seeing this issue. and fyi it happend on horizon os version prior to the current one.

**Comment by DarkMatterCore** [comment]
@Matt07211 No, it doesn't look like the same bug. Judging by the way you describe it, it also looks like you used a previous release. Latest version includes parts of the initialization code rewritten.

The bug described here affects NSP/ExeFS/RomFS dumping at least under FW 3.0.0.

**Comment by DarkMatterCore** [comment]
My latest (uncommited) changes to the codebase will make it far easier to dump gamecard NCAs through FS instead of NCM. Needs some testing, though, but I expect to fix this problem soon.

**Comment by DarkMatterCore** [comment]
Fixed in 5445d360d188c2c33935ba9c02f47acdfa902590.
