### ISSUE TITLE
Dump from SD / eMMC soft locks (probably emuMMC bug?)

### ISSUE THREAD

**Issue by ckurtz22** [DarkMatterCore/nxdumptool#29]
When I try to choose the "Dump from SD / eMMC storage" option, the application just softlocks, showing "Please wait..." and then showing an error message about no applications found on SD / eMMC for 1 frame.

**Comment by ckurtz22** [comment]
Alright, went and looked into it more. `uiProcess()` (https://github.com/DarkMatterCore/nxdumptool/blob/master/source/ui.c#L1089) will always try to run `loadTitleInfo()`. This function will always run the "please wait" if there aren't any detected titles on the system (https://github.com/DarkMatterCore/nxdumptool/blob/master/source/util.c#L1078). Since my system isn't detecting any applications install (probably due to emuMMC), each time it does a UI loop it will try to re-search for titles, instead of realizing it already searched and found nothing. I made a quick fix that probably could be cleaner, but nonetheless fixes the infinite loop. (Another solution to exiting the infinite loop is just to hold B). Made a PR with my fix here https://github.com/DarkMatterCore/nxdumptool/pull/30

**Comment by DarkMatterCore** [comment]
Thanks. I actually thought as much, but I'm far away from a PC atm.

I'll do a more clean patch when I get home. Title information buffers are freed when going back to the main menu, so using a static variable at that point might be troublesome if the user enters the menu again (assuming they do have installed titles).

**Comment by DarkMatterCore** [comment]
@ckurtz22 By the way, does any status message appear at the bottom?

**Comment by ckurtz22** [comment]
Updated PR, fixes rest of the issue. Issue was with unmounted SD card, not with emuMMC

**Comment by DarkMatterCore** [comment]
Fixed in a051b17ad070bc2cbd748de2eb7e712cb2562602.
