### ISSUE TITLE
Move nxdumptool sd folder?

### ISSUE THREAD

**Issue by ckurtz22** [DarkMatterCore/nxdumptool#31]
I feel like it would be more consistent with the rest of homebrew to move the nxdumptool folder from the root of the SD card into switch/. (Mostly just my OCD though :P )

**Comment by DarkMatterCore** [comment]
I thought about this as well, but in the end I concluded it would just be better and simpler to leave dumped data out of the /switch directory, specially considering the application does deal with directory archive bits. Kinda like Goldleaf does, except for that last part.

**Comment by DarkMatterCore** [comment]
Fixed in ba6b483cb690bccd1a43b87734683e7c1c54d8c2.
