### ISSUE TITLE
Failed to read header from Program NCA! (0x00000A05)

### ISSUE THREAD

**Issue by DakotaPixel** [DarkMatterCore/nxdumptool#33]
I am getting this error when trying to make an ExeFS section dump of the Splatoon 5.0.0 update (v2621440). What am I doing wrong?

**Comment by DarkMatterCore** [comment]
Please provide additional information about your current setup, including:

* FW version.
* CFW used.
* nxdumptool version.
* Source storage for the update (e.g. storage device where you installed the update).

A screenshot of the problem would be greatly appreciated as well.

**Comment by DakotaPixel** [comment]
FW-8.1.0
CFW-Latest Kosmos through Latest hekate emuMMC
nxdumptool-latest (idk the version offhand but I downloaded it today)
Storage- sdcard
I can't get a screenshot rn, but I should be able to tomorrow

**Comment by DarkMatterCore** [comment]
Thanks, I greatly appreciate it. I'll be waiting for it.

In the meantime, I'm going to prepare a test build with additional debug info.

**Comment by DakotaPixel** [comment]
I redownloaded the update (a couple times) and messed with some of my setup and it finally worked, don't know exactly what the problem was but I guess it is fixed now

**Comment by DarkMatterCore** [comment]
@DakotaPixel Glad to know you were able to sort it out on your own.

Nonetheless, would you please give me a more detailed explanation about what you did? If it isn't too much to ask, of course.

**Comment by DakotaPixel** [comment]
No problem, I had no luck reinstalling the game update on my old emuMMC so I deleted and recreated the emuMMC, then redownloaded the Kosmos, Hekate and nxdumptool files. After that it just worked!
