### ISSUE TITLE
Error while dumping Gamecard NSP on latest version

### ISSUE THREAD

**Issue by fantasticlain123** [DarkMatterCore/nxdumptool#35]
Hi everyone,
So I was having some issues with previous nxdumptool version (splitted nsp stuff)
and i downloaded the latest one 1.1.4 hoping it would fix some issues. But with the latest version, when i try to dump a cartidge to nsp either atmosphrere crashes or "the software was closed because an error occured". XCI dump works though.
Switch:
FW 8.1.0 using emummc 8.1.0
Hope it gets fixed

**Comment by fantasticlain123** [comment]
tested cartidges
botw, mario maker 2(both crash)
it seems that is fails in retrieving info from encrypted nca content files
also when atmosphere crashes(sometimes)(atmos version 0.9.3) the error code is 2168-0002

**Comment by DarkMatterCore** [comment]
Already reproduced and fixed. This is a segmentation fault produced by a change I forgot to revert while I was testing some stuff to fix issue #34. It's really a single line change.

Thanks for letting me know. I'll reupload the release.

**Comment by DarkMatterCore** [comment]
Fixed in 0dbe1264267308ee097b396f99ae00236e5b0089.

Please re-download the nxdumptool binary from the Releases tab.

**Comment by DarkMatterCore** [comment]
@fantasticlain123 Feel free to open up another issue to explain the problems you were having with splitted NSPs.
