### ISSUE TITLE
Add support for Korean characters.

### ISSUE THREAD

**Issue by uaevuon** [DarkMatterCore/nxdumptool#36]
![2019081718595700-BB0DD26446ABE2AC6200AA71EDDFE6EF](https://user-images.githubusercontent.com/3542715/63209881-7b67ea00-c121-11e9-84ab-66f904194a95.jpg)
![2019081719005500-BB0DD26446ABE2AC6200AA71EDDFE6EF](https://user-images.githubusercontent.com/3542715/63209882-7c008080-c121-11e9-90c3-ec0f9676a5a2.jpg)

Japanses fonts in emmc dump are OK, but Korean fonts in gamecard dump menu are crashing.

**Comment by DarkMatterCore** [comment]
Boy, for a second there you made me thought I'd have to deal with some kind of segmentation fault. I feel much relieved now.

The fonts themselves are not "crashing". The current TrueType fonts used are not compatible with Korean characters - this was an overlook on my behalf.

I'll look into it.

**Comment by DarkMatterCore** [comment]
@uaevuon Hi there. Please test the attached build, it should be fixed now.

[nxdumptool_test_20190818.zip](https://github.com/DarkMatterCore/nxdumptool/files/3513995/nxdumptool_test_20190818.zip)

**Comment by uaevuon** [comment]
> 
> 
> @uaevuon Hi there. Please test the attached build, it should be fixed now.
> 
> [nxdumptool_test_20190818.zip](https://github.com/DarkMatterCore/nxdumptool/files/3513995/nxdumptool_test_20190818.zip)

not found

**Comment by DarkMatterCore** [comment]
@uaevuon Sorry. The same thing happened a couple of days ago while dealing with another issue. My Internet connection is really bad.

Please try again.

[nxdumptool_test_20190818.zip](https://github.com/DarkMatterCore/nxdumptool/files/3514146/nxdumptool_test_20190818.zip)

**Comment by uaevuon** [comment]
It shows korean properly.
Great.

**Comment by DarkMatterCore** [comment]
Great! Thank you for reporting this issue in the first place. I'll close it as soon as I push the changes.

**Comment by DarkMatterCore** [comment]
Fixed in ba6b483cb690bccd1a43b87734683e7c1c54d8c2.

**Comment by uaevuon** [comment]
It shows title properly before dumping.
![2019101217193400-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/3542715/66698053-ba777d80-ed15-11e9-86c0-32c8c98856b7.jpg)
But it cannot show after dumping.
![2019101217201800-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/3542715/66698062-c6633f80-ed15-11e9-9a1b-488128515a33.jpg)
![주석 2019-10-12 172758](https://user-images.githubusercontent.com/3542715/66698064-c95e3000-ed15-11e9-99b4-84ef3b3e9298.jpg)

Well this is switch's own limitation, i think. Switch cannot write or read non-english character file name in sdcard.
Some games like 'Neko Tomo' don't have english title at all so they cannot be dumped with english title.
If title has non-english characters, letting users know this and making file name only include title-id might be a better way.

**Comment by DarkMatterCore** [comment]
@uaevuon It is indeed a limitation of the Switch's filesystem services. That's also the reason why many other homebrew applications can't deal with files with names that use characters outside of the 0x20 - 0x7F (ASCII) scope.

There isn't much I can do about it, sadly. But I'll see what I can do.
