### ISSUE TITLE
Please Wait error flash

### ISSUE THREAD

**Issue by Eonasdan** [DarkMatterCore/nxdumptool#42]
nxdumptool: 1.1.6
switch: 9.0.1
hekate: 5.0.2
sd card: [Samsung 128GB 100MB/s (U3) MicroSDXC Evo Select](https://www.amazon.com/gp/product/B06XWZWYVP/)

Using the tool on BotW cartridge it shows "Please Wait" for a few seconds and then flashes an error and goes back to please wait. I saw something about sd card but could make out the full error. 

Sorry for the blurriness. I had to take a video with my phone, dump that into a video editing software, step through frame by frame and take a screenshot of that lol

![image](https://user-images.githubusercontent.com/1006516/67769820-7f6e8d00-fa2b-11e9-8fa7-13f61e0c5527.png)

Managed to get another capture
![image](https://user-images.githubusercontent.com/1006516/67770479-d6289680-fa2c-11e9-98bd-9441eccb39b6.png)

**Comment by DarkMatterCore** [comment]
Please submit more information about your current setup (source storage for the game, SD card specs, etc.). I know it may be hard, but please try to screenshot the exact error as well.

**Comment by Eonasdan** [comment]
Updated my original post. Aside: you might want to look at creating [issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) with the information you're hoping to see

**Comment by DarkMatterCore** [comment]
Thanks. I will look into that.

The error is, at best, strange. Like, really strange. Are you using an emuMMC? Is your emuMMC version greater than your sysMMC version? Are you using `nogc` spoofing?

**Comment by Eonasdan** [comment]
I'm not use emuMMC. Just sfw sysnand.

I'm using `Atmosphère 0.9.4` which by default sounds like it has the ngc on. I tried to set it to 0 in the ini file.

I do get an message "The game card could not be read" from switch but I was assuming that was switch just whining about homebrew. I can't actually play the cart games at the moment, which is why I wanted to dump them and install directly. Sorry if that was the first thing I should have mentioned. I don't know why I didn't

**Comment by DarkMatterCore** [comment]
In the meantime, here's a test build that should fix the flickering UI error, as well as properly display a more detailed status message at the bottom.

[nxdumptool_20191029_t1.zip](https://github.com/DarkMatterCore/nxdumptool/files/3783964/nxdumptool_20191029_t1.zip)

**Comment by DarkMatterCore** [comment]
@Eonasdan Don't worry, it's OK. We all forget things and make mistakes. I'm just happy you took your time to open an issue. :)

Please feel free to test again with `nogc` spoofing turned off. It completely disables all I/O from the gamecard ASIC controller, and there's no way to tell if that's being used from a homebrew application.

If it doesn't work, please test the build from my previous comment. I'll be waiting.

**Comment by Eonasdan** [comment]
I disabled auto nogc from the hekate options menu. The cart error went away. I'm testing a dump of botw now.

**Comment by DarkMatterCore** [comment]
Excellent, thanks for letting me know. The flickering UI fix and a warning about `nogc` spoofing are already part of the changes for the next version.

**Comment by Eonasdan** [comment]
The dump was successful. Goldleaf failed to install the nsp but I probably didn't do it right. Either way, I've found the solution to playing from the carts and I'll have to try the dump again later.

Thanks for the help

**Comment by DarkMatterCore** [comment]
@Eonasdan Since you're using Hekate, make sure to use [Joonie86's patchset](https://github.com/Joonie86/hekate/releases) as well. It is necessary for gamecard -> NSP conversions.
