### ISSUE TITLE
Unable to generate output dump name for orphan content when no base applications are installed.

### ISSUE THREAD

**Issue by snes878** [DarkMatterCore/nxdumptool#44]
**Describe the bug**
I have a designated Switch as my “ripping” Switch; its only current purpose is to rip gamecards, updates, and DLC.  So not (currently) for playing and not for installing games onto.   

Cannot dump updates/DLC.

On 9.0.1, AMS 0.9.4, nxdumptool 1.1.7 - run under Applet mode and run under Title mode.

**To Reproduce**
1. Have no games installed to NAND or SD card - only updates and DLC.

2. Open nxdumptool to dump updates/DLC.

3. Select “Dump SD card / eMMC content”

4. Press “Y” for orphaned updates/DLC.

5.  Try to dump any updates/DLC - met with “unable to generate output dump name!"

**Work-around**
1. Install any game (possibly any application?) to NAND or SD card.

2. Return to step 3 in “to reproduce”.

3. Installed title should show up under “Dump SD card / eMMC content”.

4. Press “Y” for orphaned updates/DLC.

5. Updates/DLC should dump appropriately now.

**Please complete the following information:**
- Horizon OS (Switch FW) version: 9.0.1
- CFW: Atmosphère
- CFW version: 0.9.4
- Atmosphère launch method (if applicable): Hekate
- NXDumpTool version: 1.1.7
- Homebrew launch method: [e.g. title override / applet mode]: Both

**Comment by DarkMatterCore** [comment]
Hi there. It's a pleasure to meet you.

Thank you very for much for reporting this issue. Please try the attached test build - it should fix the problem.

[nxdumptool_20191109_t1.zip](https://github.com/DarkMatterCore/nxdumptool/files/3827350/nxdumptool_20191109_t1.zip)

If it does work, please leave the issue open. I will close this issue after the next version is released.

**Comment by snes878** [comment]
Hi, nice to meet you as well.

That totally solves the problem.   Thanks so much for such a quick fix.

**Comment by DarkMatterCore** [comment]
Thank you for reporting this problem in the first place. :)

The fix will be included in the next release.

**Comment by DarkMatterCore** [comment]
Fixed in 5445d360d188c2c33935ba9c02f47acdfa902590.
