### ISSUE TITLE
Update ticket retrieval from Secure HFS0 partition fails during NSP creation.

### ISSUE THREAD

**Issue by snes878** [DarkMatterCore/nxdumptool#45]
**Describe the bug**
While trying to dump a bundled update (possibly DLC as well, but I can't remember/reproduce that currently), met with the error "invalid parameters to retrieve file from HFS0 partition!"

**To Reproduce**
1.  NSP Dump -> Dump bundled update NSP -> all options 'Yes' -> Start NSP dump process
2. Examples of gamecards that present the issue: Sonic Mania Plus, Wasteland 2 Director's Cut, Terraria, Wargroove Deluxe Edition, Battle Chef Brigade Deluxe, and Hollow Knight (most recent copy from Fan Gamer with all DLC's on the cart.)

**Please complete the following information:**
- Horizon OS (Switch FW) version: 9.0.1
- CFW: Atmosphère
- CFW version: 0.9.4
- Atmosphère launch method: Hekate
- NXDumpTool version: 1.1.7
- Homebrew launch method: title override
- Source storage used with the application (if applicable): gamecard
- SD card specs: Sandisk 400 GB micro SD

**Additional context**

**Note:** Installed NSP updates dump just fine.  If downloaded from the eShop, the update will dump just fine from the orphan updates/DLC submenu.  If downloaded from (elsewhere) and installed via Goldleaf, the update will dump just fine from the orphan updates/DLC submenu.  But if the gamecard contains the latest update (like Sonic Mania Plus, Wargroove Deluxe Edition, and Hollow Knight, etc.) there is no way to trigger the eShop to download the update separately.  So no current workaround has been discovered by myself, other than sourcing the updates from elsewhere and installing via Goldleaf, which will then produce a dump-able orphan update.

**Comment by DarkMatterCore** [comment]
Hi there. Thanks for reporting this issue.

Granted, it's an easy fix. This is a bug introduced in v1.1.7 after I refactored the content record retrieval code. Please test the attached build.

[nxdumptool_20191111_t1.zip](https://github.com/DarkMatterCore/nxdumptool/files/3832852/nxdumptool_20191111_t1.zip)

**Comment by snes878** [comment]
That solved it - thanks again!

**Comment by DarkMatterCore** [comment]
@snes878 Thank you for reporting these problems in the first place!

**Comment by DarkMatterCore** [comment]
Fixed in 5445d360d188c2c33935ba9c02f47acdfa902590.
