### ISSUE TITLE
ES certificate retrieval procedure fails if there's no personalized ticket certificate.

### ISSUE THREAD

**Issue by potchy** [DarkMatterCore/nxdumptool#46]
**Describe the bug**
I get this "Unable to find FS index from key" error whenever I try to dump my already installed games.
It only happens on 1.1.7. Version 1.1.6 seems to work fine. The procedure isn't finished yet, but it's at 3/108 at the moment.

**To Reproduce**
1. Dump SD card / eMMC (NANDUSER) content
2. Press X to enter batch mode
3. Start batch dump process (leave everything on default)

**Screenshots**
![2019112415035600-3C66B776DB1AA06323037049FACD96D3](https://user-images.githubusercontent.com/4316326/69498219-da2cc480-0ec3-11ea-8390-ca6d02b1f89c.jpg)

**Please complete the following information:**
- Horizon OS (Switch FW) version: 9.0.0
- CFW: Atmosphère
- CFW version: I'm not sure, but it's probably 0.9.4
- Atmosphère launch method (if applicable): Hekate
- NXDumpTool version: 1.1.7
- Homebrew launch method: Title override
- Source storage used with the application (if applicable): SD
- SD card specs: Alfawise 256GB

**Additional context**
[Here's my prod.keys file that I dumped today](https://github.com/DarkMatterCore/nxdumptool/files/3883873/prod.keys.txt) with Lockpick_RCM 1.7.1. I had to put a .txt at the end, otherwise GitHub wouldn't let me upload it.

**Comment by DarkMatterCore** [comment]
It's a known problem that has been fixed already in test builds. This only occurs if you haven't downloaded/bought anything from the eShop.

**Comment by DarkMatterCore** [comment]
In the meantime, feel free to try the latest test build.

[nxdumptool_20191124_t1.zip](https://github.com/DarkMatterCore/nxdumptool/files/3884056/nxdumptool_20191124_t1.zip)

**Comment by DarkMatterCore** [comment]
Fixed in 5445d360d188c2c33935ba9c02f47acdfa902590.
