### ISSUE TITLE
Titlekey decryption failure with installed CDNSP dump.

### ISSUE THREAD

**Issue by Zet-sensei** [DarkMatterCore/nxdumptool#47]
**Describe the bug**
Invalid magic word for Program NCA section #0 PSF0 partition! Wrong KAEK ? (0xE2603D03)

**Screenshots**
![2019120817592900](https://user-images.githubusercontent.com/52127625/70850392-fb148400-1e89-11ea-8133-0b9581ea859b.jpg)

**Please complete the following information:**
- Horizon OS (Switch FW) version: 9.1.0 emuNAND
- CFW: SX OS
- CFW version: 2.9.3
- NXDumpTool version: 1.1.8
- Homebrew launch methods: title override & Album applet
- Source storage used with the application (if applicable): SD/eMMC
- SD card specs: SanDisk Ultra microSDXC UHS-I 400 GB

**Additional context**
I wanted to dump a specific game for future preservation purposes (Earthworms).
When I launch the dumping process, a message error appears.
I've redumped my personal prod.keys with the last LockPick_RCM for FW 9.1.0 and verified all the values.
No problem with any other games to dump, just that specific one.

**Comment by DarkMatterCore** [comment]
Please try running the v1.1.8 stable release (which is more recent than the one you're using) and report back.

**Comment by Zet-sensei** [comment]
Same problem.

I took the screenshot and saw the problem on the previous dev one just before you released the stable 1.18 version, but the problem remains even on the stable one.
That's why I'm reporting the problem now.

**Comment by DarkMatterCore** [comment]
Feel free to send me a messsage through Discord. It'll be easier for both of us to track down the problem that way.

My handle is `DarkMatterCore#4814`.

**Comment by DarkMatterCore** [comment]
Status update: the Earthworms installation actually comes from a CDNSP dump with a forged common ticket. Even though the plaintext encrypted titlekey can be retrieved without any problems, the decrypted titlekey doesn't work.

Even more so, according to the Earthworms dump from another user, the plaintext encrypted titlekey doesn't match.

More tests will be performed after the holidays. Happy new year.

**Comment by DarkMatterCore** [comment]
The application is being rewritten from scratch using a temporary private repository to improve things such as code quality, code maintenance and code readability.

Bug reports and feature requests will remain open to keep track of what's missing as hopefully add them to the new codebase.

**Comment by DarkMatterCore** [comment]
@Zet-sensei I'd love to give this another try using a test build based on the rewrite codebase. I'd be very grateful if you could help me out yet again.

**Comment by DarkMatterCore** [comment]
@Zet-sensei I'm temporarily closing this issue. If you have the time, feel free to reopen it so I can take a better look at the problem.
