### ISSUE TITLE
Unable to dump games on non-primary console

### ISSUE THREAD

**Issue by TechGeekGamer** [DarkMatterCore/nxdumptool#48]
**Describe the bug**
When trying to dump games on a secondary console, it would give an error

**To Reproduce**
1. Go to `Dump installed SD card / eMMC content`
2. Click on `Any of the games downloaded from the eShop`
3. Click on `Nintendo Submission Package (NSP) dump`
4. Click on `Dump base application` (if updates are installed)
5. Click on `Start NSP dump process`
6. See error

**Screenshots**
Will post in a few minutes.

**Please complete the following information:**
- HOS 9.1.0
- Atmosphere CFW
- Atmosphere 10.1
- Hekate 5.1.1 + NYX 0.8.4
- NXDumpTool version: 1.1.8
- Title override
- SD content
- SD card specs: Samsung EVO 128 GB

**Additional context**
-

**Comment by DanielC-08** [comment]
![38AE1DDC-CB0A-4649-8A6B-4664B52D3A6C](https://user-images.githubusercontent.com/46201432/71137086-cec77300-21bb-11ea-97e5-d33efe816d99.jpeg)

**Comment by DanielC-08** [comment]
Testing 12/21/2019 12:50PM PST: When switching primary console to secondary and vice versa the now secondary console has the same error.

**Comment by DarkMatterCore** [comment]
The application is being rewritten from scratch using a temporary private repository to improve things such as code quality, code maintenance and code readability.

Bug reports and feature requests will remain open to keep track of what's missing as hopefully add them to the new codebase.

**Comment by TechGeekGamer** [comment]
Workaround: Switch console to primary, dump keys using Lockpick_RCM, (if you still want to) switch back to non-primary console.

**Comment by pcwizard7** [comment]
on secondary consoles, the games don't store the titlekey for the game which is why it checks online before it boots

**Comment by DarkMatterCore** [comment]
@TechGeekGamer @pcwizard7 `Bigkahuna666#9097` from Discord discovered that if you launch a shared game and let it retrieve the titlekey from the eShop, then press Home and launch nxdumptool via applet mode, you \*can\* dump shared game data without any major issues. This only works while the game is running, though.

**Comment by DarkMatterCore** [comment]
Lauching nxdumptool using title override on the shared game you wish to dump also works.

**Comment by DarkMatterCore** [comment]
Games shared across different consoles, timed NSO trials and some other special titles require an Internet connection to be launched, because their ticket isn't permanently stored in the console. The workarounds found by `Bigkahuna666` are valid for all these cases.

There's nothing I can do about this except for adding warnings to the application. I'll close this issue.
