### ISSUE TITLE
Can't dump games from SD/eMMC

### ISSUE THREAD

**Issue by failsafe42** [DarkMatterCore/nxdumptool#49]
**Describe the bug**
Can't dump installed games. prod.keys exists and is not empty but I get an error trying to dump the games: "loadExternalKeys: unable to parse necessary keys from 'sdmc:/switch/prod.keys'! (keys file empty?)"

**To Reproduce**
1. Go to 'Dump installed SD card / eMMC content'
2. Click on a game
3. Click dump
4. Click start
5. See error

----------------------------------------------------------

- Horizon OS (Switch FW) version: 9.1.0
- CFW: Atmosphere
- CFW version: 10.1
- Atmosphère launch method (if applicable): fusee-primary
- NXDumpTool version: 1.1.8
- Homebrew launch method: title override and Album applet
- Source storage used with the application (if applicable): SD/eMMC
- SD card specs: Samsung EVO Select 256 GB

**Comment by DarkMatterCore** [comment]
Which method did you use to generated the prod.keys file? You can't just copypaste a keys file from the Internet, just in case.

**Comment by failsafe42** [comment]
I used lockpick

**Comment by DarkMatterCore** [comment]
The homebrew NRO that can be launched from hbloader? Or the payload version that's launched via RCM?

You shouls use the second one.

**Comment by failsafe42** [comment]
It seems that was the problem. I was using the nro version. I dumped them with the rcm payload and it works.

**Comment by DarkMatterCore** [comment]
Glad to know it. :)

I'll close this issue, in that case. Feel free to create a new one if you run into a different problem.

**Comment by failsafe42** [comment]
When I try to install the nsp that I dumped it doesn't start. It just says "Checking if the software can be played...". Any Ideas?

**Comment by DarkMatterCore** [comment]
I suppose you installed your dump to another console. Are you using ES/FS patches on it?

**Comment by failsafe42** [comment]
Trying to install it to another emummc and I do have the patches.

**Comment by failsafe42** [comment]
Removed console specific data and now it works. Now I have to ask: how come goldleaf can't do that?

**Comment by DarkMatterCore** [comment]
Goldleaf does what it is supposed to do: install the contents from any NSPs it is provided with.

This kind of modifications are usually done when the NSP is created.

**Comment by failsafe42** [comment]
I meant that goldleaf has the ability to dump games, so why can't it remove console specific data while doing that?

**Comment by DarkMatterCore** [comment]
It *could* do it, but it's not a dump-oriented tool like this one, so it doesn't offer as many options. It's natural.
