### ISSUE TITLE
Dump from SD: Games missing from SysNAND

### ISSUE THREAD

**Issue by NickHatBoecker** [DarkMatterCore/nxdumptool#52]
Hey guys,

I have SysNAND and EmuNAND.
On EmuNAND I have the CFW (SX OS) with nxdumptool.

When I choose to "dump installed SD card / eMMC content" I only get the games I installed on emuNAND, but I want to dump a game update of graveyard keeper, which I bought in the eshop on sysNAND.

So I want to copy the update from sysNAND to emuNAND. Is this possible with nxdumptool?

Thanks in advance and best regards
Nick

**Comment by DarkMatterCore** [comment]
Hi there. Nice to meet you.

Sadly, emuMMC redirection makes all sysMMC access impossible. If you wish to use this or any other apps capable of reading eMMC data with your sysMMC, you must run a CFW on your sysMMC.

It's not somethinf that can (nor will) be fixed.
