### ISSUE TITLE
A configurable option is also available to remove console specific data from dumped tickets.

### ISSUE THREAD

**Issue by Ghostk0** [DarkMatterCore/nxdumptool#55]
Hello, I would like to understand what this option corresponds to "A configurable option is also available to remove console specific data from dumped tickets." ?
Is information from my consoles kept in the XCI / NSP file that I dump?

**Comment by DarkMatterCore** [comment]
@Ghostk0 Hi there, nice to meet you.

Gamecards don't hold any kind of console-specific data, so all XCI/NSP dumps generated from one are entirely clean.

NSP dumps from installed digital titles, on the other hand, *do* hold contain console-specific data in their tickets. However, if you choose to enable the "Remove console specific data" option, this data will be completely wiped.

**Comment by Ghostk0** [comment]
Hello DarkMatterCore,

Ok I understood what it is.
I thank you.
