### ISSUE TITLE
ES savefile processing crashes under 10.0.0.

### ISSUE THREAD

**Issue by snes878** [DarkMatterCore/nxdumptool#56]
**Describe the bug**
If I try to dump update v196608 (0.0.3.0) for the Amnesia: Collection as an NSP, the interface hangs at “Retrieving information from encrypted NCA content files...”   And then NXDumpTool crashes.   Sometimes Atmosphere crashes.

**Edit:**  I should preface by saying that this is regarding a genuine eShop copy of the game. 

**To Reproduce**
1. Start NXDumpTool 1.1.9 (either title override or applet mode)
2. Dump installed SD card / eMMC content
3. Choose Amnesia: Collection
4. NSP Dump
5. Dump installed update NSP
6. Start NSP dump process

**Please complete the following information:**
- Horizon OS (Switch FW) version: 10.0.0
- CFW: Atmosphère
- CFW version: 0.11.1
- Atmosphère launch method (if applicable): Hekate v5.1.4
- NXDumpTool version: 1.1.9
- Homebrew launch method: Tried under both title override and applet mode methods.
- Source storage used with the application (if applicable): SD card/eMMC
- SD card specs: Sandisk Ultra A1 400 GB

**Additional context**
I think other title updates are ripping correctly.   I’ll add further examples if I come across them.

**Comment by DarkMatterCore** [comment]
@snes878 Hi there, mate. Thanks for reporting this issue.

Could you please provide an Atmosphère crash report? It would be very helpful to pinpoint the exact source of the problem in the codebase.

**Comment by snes878** [comment]
Hi - thanks for the quick reply.  I can’t get it to display an Atmosphere error message during title mode, but I can reproduce it on applet mode if I try to press Home to get out, and then try to go back into the album.

![2020041721001100-EA167CCACA37E364FF7957C68F12AA0E](https://user-images.githubusercontent.com/57560425/79625593-9b580f00-80ef-11ea-9d2b-568eafc7ecbb.jpg)

![146D3AB7-1580-4103-AD6D-B01E27AA9329](https://user-images.githubusercontent.com/57560425/79625606-add24880-80ef-11ea-98e8-cb777e5c8a66.jpeg)

**Comment by snes878** [comment]
Looks like the same issue when trying to dump the latest Cuphead title update, too.

**Comment by DarkMatterCore** [comment]
Crash reports are automatically generated by Atmosphère and saved to the `/atmosphere/crash_reports/` directory.

**Comment by snes878** [comment]
Here’s a c/p of my most recent one:

Atmosphère Crash Report (v1.5):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                hbloader
    Program ID:                  0100701001d92000
    Process ID:                  0000000000000085
    Process Flags:               00000073
    User Exception Address:      0000000018f98000
Exception Info:
    Type:                        Data Abort
    Address:                     00000000000001a0
    Fault Address:               0000000000000000
Crashed Thread Info:
    Thread ID:                   000000000000020b
    Stack Region:                0000000016252000-0000000016352000
    Registers:
        X[00]:                   00000005d874d000
        X[01]:                   0000000b22642110
        X[02]:                   0000000000000190
        X[03]:                   0000000000000000
        X[04]:                   0000000b226422a0
        X[05]:                   00000005d875e5f0
        X[06]:                   0000000000000000
        X[07]:                   0000000b226422a0
        X[08]:                   0000000b22642110
        X[09]:                   7f7f7f7f7f7f7f7f
        X[10]:                   fefefefefefefeff
        X[11]:                   7f7f7f7f7f7f7f7f
        X[12]:                   0101010101010101
        X[13]:                   21534620656c6966
        X[14]:                   0000000000000000
        X[15]:                   0000000000000008
        X[16]:                   0000000000000000
        X[17]:                   fffffffffffffff0
        X[18]:                   0000000000000000
        X[19]:                   0000000b226422b0
        X[20]:                   00000005d875dc60
        X[21]:                   0000000000000040
        X[22]:                   0000000000000002
        X[23]:                   0000000b22641970
        X[24]:                   0000000000004000
        X[25]:                   00000005d868a000
        X[26]:                   000000001634cec8
        X[27]:                   00000005d8763a1c
        X[28]:                   000000001634cc10
        FP:                      000000001634c5b0
        LR:                      00000005d866886c (nxdumptool + 0x1e086c)
        SP:                      000000001634c5b0
        PC:                      00000005d86688bc (nxdumptool + 0x1e08bc)
    Stack Trace:
        ReturnAddress[00]:       00000005d84ada14 (nxdumptool + 0x25a14)
        ReturnAddress[01]:       00000005d84ade9c (nxdumptool + 0x25e9c)
        ReturnAddress[02]:       00000005d849f148 (nxdumptool + 0x17148)
        ReturnAddress[03]:       00000005d84a14f0 (nxdumptool + 0x194f0)
        ReturnAddress[04]:       00000005d848b27c (nxdumptool + 0x327c)
        ReturnAddress[05]:       00000005d84bcae4 (nxdumptool + 0x34ae4)
        ReturnAddress[06]:       00000005d8488230 (nxdumptool + 0x230)
        ReturnAddress[07]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[08]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[09]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[10]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[11]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[12]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[13]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[14]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[15]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[16]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[17]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[18]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[19]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[20]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[21]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[22]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[23]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[24]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[25]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[26]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[27]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[28]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[29]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[30]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[31]:       00000005d84881c0 (nxdumptool + 0x1c0)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00001634c5b0 d0 c5 34 16 00 00 00 00 14 da 4a d8 05 00 00 00
                                 00001634c5c0 02 00 00 00 00 00 00 00 70 d9 63 22 0b 00 00 00
                                 00001634c5d0 00 c6 34 16 00 00 00 00 9c de 4a d8 05 00 00 00
                                 00001634c5e0 70 d9 63 22 0b 00 00 00 70 c6 34 16 00 00 00 00
                                 00001634c5f0 00 d0 74 d8 05 00 00 00 98 1b 64 22 0b 00 00 00
                                 00001634c600 80 ca 34 16 00 00 00 00 48 f1 49 d8 05 00 00 00
                                 00001634c610 07 00 00 00 00 00 00 00 70 d9 63 22 0b 00 00 00
                                 00001634c620 f0 0c 35 16 00 00 00 00 dd f4 34 16 00 00 00 00
                                 00001634c630 fd fb 34 16 00 00 00 00 ed f4 34 16 00 00 00 00
                                 00001634c640 00 a0 68 d8 05 00 00 00 00 00 00 00 00 00 00 00
                                 00001634c650 00 00 00 00 00 00 00 00 00 00 00 00 20 00 00 00
                                 00001634c660 d5 75 98 b6 7b 4a d7 fd ab 83 e9 c7 f0 01 40 86
                                 00001634c670 0a 73 61 76 65 5f 70 72 6f 63 65 73 73 3a 20 66
                                 00001634c680 61 69 6c 65 64 20 74 6f 20 69 6e 69 74 69 61 6c
                                 00001634c690 69 7a 65 20 73 61 76 65 66 69 6c 65 20 46 53 21
                                 00001634c6a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 0000000018f98200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 000018f98200 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98210 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98220 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98230 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98240 00 00 3f 04 00 00 00 00 00 02 00 00 00 00 00 00
                                 000018f98250 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98260 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98270 12 00 00 00 00 00 00 00 85 00 00 00 00 00 00 00
                                 000018f98280 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           1
    Module 00:
        Address:                 00000005d8488000-00000005d8687000
        Name:                    nxdumptool
        Build Id:                78FE2CC45CFEDA1A07EAFC6E2D08749882B2C376000000000000000000000000
Thread Report:
Number of Threads:               02
Threads[00]:
    Thread ID:                   000000000000020b
    Stack Region:                0000000016252000-0000000016352000
    Registers:
        X[00]:                   00000005d874d000
        X[01]:                   0000000b22642110
        X[02]:                   0000000000000190
        X[03]:                   0000000000000000
        X[04]:                   0000000b226422a0
        X[05]:                   00000005d875e5f0
        X[06]:                   0000000000000000
        X[07]:                   0000000b226422a0
        X[08]:                   0000000b22642110
        X[09]:                   7f7f7f7f7f7f7f7f
        X[10]:                   fefefefefefefeff
        X[11]:                   7f7f7f7f7f7f7f7f
        X[12]:                   0101010101010101
        X[13]:                   21534620656c6966
        X[14]:                   0000000000000000
        X[15]:                   0000000000000008
        X[16]:                   0000000000000000
        X[17]:                   fffffffffffffff0
        X[18]:                   0000000000000000
        X[19]:                   0000000b226422b0
        X[20]:                   00000005d875dc60
        X[21]:                   0000000000000040
        X[22]:                   0000000000000002
        X[23]:                   0000000b22641970
        X[24]:                   0000000000004000
        X[25]:                   00000005d868a000
        X[26]:                   000000001634cec8
        X[27]:                   00000005d8763a1c
        X[28]:                   000000001634cc10
        FP:                      000000001634c5b0
        LR:                      00000005d866886c (nxdumptool + 0x1e086c)
        SP:                      000000001634c5b0
        PC:                      00000005d86688bc (nxdumptool + 0x1e08bc)
    Stack Trace:
        ReturnAddress[00]:       00000005d84ada14 (nxdumptool + 0x25a14)
        ReturnAddress[01]:       00000005d84ade9c (nxdumptool + 0x25e9c)
        ReturnAddress[02]:       00000005d849f148 (nxdumptool + 0x17148)
        ReturnAddress[03]:       00000005d84a14f0 (nxdumptool + 0x194f0)
        ReturnAddress[04]:       00000005d848b27c (nxdumptool + 0x327c)
        ReturnAddress[05]:       00000005d84bcae4 (nxdumptool + 0x34ae4)
        ReturnAddress[06]:       00000005d8488230 (nxdumptool + 0x230)
        ReturnAddress[07]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[08]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[09]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[10]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[11]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[12]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[13]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[14]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[15]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[16]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[17]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[18]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[19]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[20]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[21]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[22]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[23]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[24]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[25]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[26]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[27]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[28]:       00000005d84881c0 (nxdumptool + 0x1c0)
        ReturnAddress[29]:       00000005d85af3b4 (nxdumptool + 0x1273b4)
        ReturnAddress[30]:       00000005d8488224 (nxdumptool + 0x224)
        ReturnAddress[31]:       00000005d84881c0 (nxdumptool + 0x1c0)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00001634c5b0 d0 c5 34 16 00 00 00 00 14 da 4a d8 05 00 00 00
                                 00001634c5c0 02 00 00 00 00 00 00 00 70 d9 63 22 0b 00 00 00
                                 00001634c5d0 00 c6 34 16 00 00 00 00 9c de 4a d8 05 00 00 00
                                 00001634c5e0 70 d9 63 22 0b 00 00 00 70 c6 34 16 00 00 00 00
                                 00001634c5f0 00 d0 74 d8 05 00 00 00 98 1b 64 22 0b 00 00 00
                                 00001634c600 80 ca 34 16 00 00 00 00 48 f1 49 d8 05 00 00 00
                                 00001634c610 07 00 00 00 00 00 00 00 70 d9 63 22 0b 00 00 00
                                 00001634c620 f0 0c 35 16 00 00 00 00 dd f4 34 16 00 00 00 00
                                 00001634c630 fd fb 34 16 00 00 00 00 ed f4 34 16 00 00 00 00
                                 00001634c640 00 a0 68 d8 05 00 00 00 00 00 00 00 00 00 00 00
                                 00001634c650 00 00 00 00 00 00 00 00 00 00 00 00 20 00 00 00
                                 00001634c660 d5 75 98 b6 7b 4a d7 fd ab 83 e9 c7 f0 01 40 86
                                 00001634c670 0a 73 61 76 65 5f 70 72 6f 63 65 73 73 3a 20 66
                                 00001634c680 61 69 6c 65 64 20 74 6f 20 69 6e 69 74 69 61 6c
                                 00001634c690 69 7a 65 20 73 61 76 65 66 69 6c 65 20 46 53 21
                                 00001634c6a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 0000000018f98200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 000018f98200 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98210 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98220 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98230 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98240 00 00 3f 04 00 00 00 00 00 02 00 00 00 00 00 00
                                 000018f98250 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98260 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98270 12 00 00 00 00 00 00 00 85 00 00 00 00 00 00 00
                                 000018f98280 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f982f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Threads[01]:
    Thread ID:                   0000000000000213
    Stack Region:                0000000008000000-0000000008021000
    Registers:
        X[00]:                   000000000801ff4c
        X[01]:                   000000000801fdd0
        X[02]:                   0000000000000002
        X[03]:                   ffffffffffffffff
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      000000000801fde0
        LR:                      00000005d85ac5a4 (nxdumptool + 0x1245a4)
        SP:                      000000000801fd60
        PC:                      00000005d85c0fcc (nxdumptool + 0x138fcc)
    Stack Trace:
        ReturnAddress[00]:       00000005d85ac3c8 (nxdumptool + 0x1243c8)
        ReturnAddress[01]:       00000005d84bf83c (nxdumptool + 0x3783c)
        ReturnAddress[02]:       00000005d85c9208 (nxdumptool + 0x141208)
        ReturnAddress[03]:       00000005d85ca08c (nxdumptool + 0x14208c)
        ReturnAddress[04]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00000801fd60 4c ff 01 08 00 00 00 00 ff ff ff ff 00 00 00 00
                                 00000801fd70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00000801fd80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00000801fd90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00000801fda0 00 71 76 d8 05 00 00 00 00 71 76 d8 05 00 00 00
                                 00000801fdb0 f8 70 76 d8 05 00 00 00 25 80 34 00 00 00 00 00
                                 00000801fdc0 74 fe 01 08 00 00 00 00 01 00 00 00 00 00 00 00
                                 00000801fdd0 23 00 34 00 25 80 34 00 00 00 00 00 00 00 00 00
                                 00000801fde0 80 fe 01 08 00 00 00 00 c8 c3 5a d8 05 00 00 00
                                 00000801fdf0 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00
                                 00000801fe00 4c ff 01 08 00 00 00 00 50 ff 01 08 00 00 00 00
                                 00000801fe10 00 c4 5a d8 05 00 00 00 71 02 00 00 00 00 00 00
                                 00000801fe20 01 ea 00 00 00 00 00 00 ab aa aa aa aa aa aa aa
                                 00000801fe30 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00000801fe40 4c ff 01 08 00 00 00 00 50 ff 01 08 00 00 00 00
                                 00000801fe50 70 fd 01 08 00 00 00 00 df fe 01 08 02 00 00 00
    TLS Address:                 0000000018f98400
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 000018f98400 00 00 00 00 0d 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98410 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98420 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98430 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98440 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98450 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98460 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98470 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98480 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f98490 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f984a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f984b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f984c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f984d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f984e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000018f984f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by DarkMatterCore** [comment]
@snes878 Thanks, that really helped me out. Please test the attached build and let me know how it goes.

[nxdumptool_20200417_t1.zip](https://github.com/DarkMatterCore/nxdumptool/files/4495949/nxdumptool_20200417_t1.zip)

**Comment by snes878** [comment]
I don't have time this weekend to thoroughly test it out - but so far, it seems like you fixed it.  Thanks again for such a quick turn around time!   =D

**Comment by DarkMatterCore** [comment]
@snes878 Thanks for confirming the crash has been fixed. :)

I'll close this issue as soon as the new version is released.

**Comment by DarkMatterCore** [comment]
The test build was confirmed to be working without any issues by other users.

Fixed in ff3141f5d6e2a5cbb59e1e8815f03fe0e160e89f.
