### ISSUE TITLE
VideoCapture mode naming is inconsistent with switchbrew

### ISSUE THREAD

**Issue by ckurtz22** [DarkMatterCore/nxdumptool#61]
https://github.com/DarkMatterCore/nxdumptool/blob/a999447580fd1ac6a53d4ab6320856f6cfc66d8c/source/nca.c#L2594

I'm not sure if one is necessarily "correct", but it is inconsistent with switchbrew which just caused me a lot of confusion (thought the "Enabled" in the xml produced meant manual mode). Here is [switchbrew page](https://switchbrew.org/wiki/NACP_Format#VideoCapture)

**Comment by DarkMatterCore** [comment]
Switchbrew information isn't used to generate AuthoringTool-like Control XMLs. This is all based on the 010 Editor template available [here](https://github.com/0Liam/switch-010editor-templates/blob/master/NACP.bt).
