### ISSUE TITLE
“readBktrSectionBlock: BKTR references non-existent base Rom-FS section!” 

### ISSUE THREAD

**Issue by sharrenskunk** [DarkMatterCore/nxdumptool#63]
Fully upgraded all tools, switch fw version & am running it through hekate, non applet mode. 

Trying to use nxdump tool, I already dumped the game (I kind of miss placed it and is no longer on my SD card)and am trying to dump it with the update/dlc and it’s giving me an error “readBktrSectionBlock: BKTR references non-existent base Rom-FS section!” 
![52B9A02E-C1EA-4745-9ADF-5843CD7AF281](https://user-images.githubusercontent.com/72164166/94730781-99d67800-0318-11eb-84e9-e388ae45c6c3.jpeg)

It looks like it’s looking for an NCA Program for the update/DLC and can’t find it, but when dumping it with no update/DLC it allows me to dump the RomFS.

**Comment by sharrenskunk** [comment]
Do I need to redo my emuMMC since it can’t find the base application or update for some reason?

**Comment by DarkMatterCore** [comment]
Redownload the latest NRO from the Releases section and try again. There was a borked condition check I fixed some hours after publishing the release.

**Comment by sharrenskunk** [comment]
It still gives me that same error

**Comment by sharrenskunk** [comment]
It still gives me the same error. I copied all content from my Nintendo folder into my raw1 folder so I can have all game data on my emummc and tried to rerun the dump and it gives me that same error. 

I deleted the nro and put the one from here and it still gives “ readBktrSectionBlock: BKTR references non-existent base Rom-FS section” error

**Comment by sharrenskunk** [comment]
If you already dumped a games RomFS and removed it from the SD card completely can you re-dump a game? Because it’s not letting me unfortunately.

**Comment by DarkMatterCore** [comment]
@sharrenskunk Sorry, please try again. I uploaded the right NRO this time around.

**Comment by sharrenskunk** [comment]
@DarkMatterCore how recent? I updated my nro a few hours ago when you said to. I’ll check again in the morning.

**Comment by sharrenskunk** [comment]
Hey thanks for the fix! It’s working now <3
