### ISSUE TITLE
NCA files

### ISSUE THREAD

**Issue by sharrenskunk** [DarkMatterCore/nxdumptool#64]
Used latest nro and the NCA files aren't showing up. The dump is short files so it cannot be used in PkNx.

**Comment by DarkMatterCore** [comment]
@sharrenskunk 

Individual NCA listing + dumping per title isn't available in the application. This is a planned feature for the ongoing [rewrite](https://github.com/DarkMatterCore/nxdumptool/tree/rewrite).

In the meantime, you can dump a NSP for the title you wish to get the NCAs from, then unpack it in your PC to get those NCAs.

**Comment by sharrenskunk** [comment]
@DarkMatterCore 

I deleted the dump last night and it worked. It was randomly missing files.
