### ISSUE TITLE
readBktrSectionBlock: BKTR references non-existent base RomFS Section

### ISSUE THREAD

**Issue by ChocoCheeese07** [DarkMatterCore/nxdumptool#65]
First, I know this issue seems to have been resolved in [this issue](https://github.com/DarkMatterCore/nxdumptool/issues/63), but I seem to be having the same problem. Was the fix uploaded to the app store version as well?

**Comment by ChocoCheeese07** [comment]
I had to update the application from the app. Didn't think it would do anything cause it said I was on the latest version.

**Comment by DarkMatterCore** [comment]
@ChocoCheeese07 There was a hotfix that didn't bump the version number, yeah. Forcing an update from the application itself is equivalent to getting the latest NRO from this repository on your own.
