### ISSUE TITLE
Failing when dumping an installed title on sysnand

### ISSUE THREAD

**Issue by putzritsu** [DarkMatterCore/nxdumptool#66]
**Describe the bug**
I dumped the keys with Lockpick_RCM, but when i try to dump the demo for Kingdom Hearts Melody of Memory it shows "invalid public RSA exponent for eTicket data! Wrong keys?

**To Reproduce**
1. Go to 'Dumo installed SD card / eMMC content'
2. Click on 'Kingdom Hearts Melody of Memory DEMO Version'
3. Click on 'Nintendo Submission Package (NSP) dump'
4. Click on 'Start NSP dump procces'
5. See error

**Please fill the following information:**
- Horizon OS (Switch FW) version: 10.2.0
- CFW: Atmosphere
- CFW version: 0.14.4
- Atmosphère launch method (if applicable): Hekate
- NXDumpTool version: 1.1.12
- Homebrew launch method: Title overide
- Source storage used with the application (if applicable): SD 
- SD card specs: Sandisk Ultra 128GB Fat32

![image](https://user-images.githubusercontent.com/69218835/96210242-e12f4c00-0f47-11eb-9bc2-8b940a9e2d93.png)

**Comment by DarkMatterCore** [comment]
@putzritsu Hi there, nice to meet you.

Are you using a Mariko unit with a SX Core?

**Comment by putzritsu** [comment]
@DarkMatterCore Hi, I'm glad to meet you two! No, I'm using a unpatched switch running atmosphere.

**Comment by Whovian9369** [comment]
No issue here with dumping it on sysNAND *without* an emuNAND on AMS 0.14.4 and NXDumpTool v1.1.12!
![2020101704164300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/5240754/96331993-a3a5ee00-102f-11eb-9131-2a6d0dc7e14a.jpg)

**Comment by DarkMatterCore** [comment]
Hmm. I'm suspecting this might actually be an issue related to Lockpick_RCM, then.

@shchmue (sorry for tagging you!) Any thoughts?

**Comment by shchmue** [comment]
No problem, does the `sd:/switch/prod.keys` file contain an `eticket_rsa_kek`?

**Comment by putzritsu** [comment]
@shchmue No it doesn't, just checked. And other games don't work too, the problem probably are the prod.keys file, but idk how i messed it up because i did everything right.

**Comment by shchmue** [comment]
did Lockpick_RCM display any errors? did you run the latest version?

**Comment by putzritsu** [comment]
As far as I know, no, and yes I did run the lastest version.
![image](https://user-images.githubusercontent.com/69218835/96352650-37f96a80-109b-11eb-91c9-f79da61f5c37.png)

**Comment by shchmue** [comment]
That's not the latest version, and it displays an error. The latest version fixes an issue that was created by an Atmosphere update. Using version 1.8.4 of Lockpick_RCM should result in a full key dump.

**Comment by putzritsu** [comment]
'Kay, i'll try, sorry for the inconvenience

**Comment by DarkMatterCore** [comment]
@putzritsu Where you able to get it working after updating Lockpick_RCM?

**Comment by putzritsu** [comment]
@DarkMatterCore Sorry for the late response. Yes I was! I'm really sorry for the inconvenience and I need to thank you and @shchmue for the help.
