### ISSUE TITLE
Dump to NSZ

### ISSUE THREAD

**Issue by KAMELCOLTD** [DarkMatterCore/nxdumptool#67]
Hi 
Was wondering  if you can add support to dump a game to nsz would be great! 
i really wanted it less space and powerful

**Comment by DarkMatterCore** [comment]
Hi there. Nice to meet you.

This feature overly complicates the whole NSP dumping process, and can potentially slow it down. The compression scheme used by the NSZ format requires little processing power to decompress, but a powerful CPU to achieve good compression rates.

This has been discussed in the past, although not in this issue tracker. I don't really think it'd be worth it to implement it, even more so considering one of the aspects the rewrite is focused on is _speed_ (which is already at a pretty good state).

The rewrite will be able to send NSPs to a connected USB host device (PC, smart device, etc.) right at the same time as they're being dumped. No SD card storage space will be used in the process.
