### ISSUE TITLE
Can't dump Pokémon Sword romfs with Crown Tundra installed

### ISSUE THREAD

**Issue by melsbacksfriend** [DarkMatterCore/nxdumptool#68]
**Describe the bug**

When I try dumping, I'm greeted with this screen: 

**To Reproduce**
1. Go to dump installed sd card emmc content
2. Click on Pokémon Sword
3. Choose romfs options
4. Use the update
5. Choose romfs section data dump

**Please fill the following information:**
- Horizon OS (Switch FW) version: 10.1.0
- CFW: Atmosphère
- CFW version: 0.14.4
- Atmosphère launch method (if applicable): fusee-primary
- NXDumpTool version: v1.1.12
- Homebrew launch method: Homebrew Details
- Source storage used with the application (if applicable): eMMC
- SD card specs: Samsung EVO 512GB FAT32

**Screenshots**
Add screenshots to help explain your problem.

![20201029_082904](https://user-images.githubusercontent.com/36408599/97580057-d69d9980-19c0-11eb-8bf5-14e302d9f0ee.jpg)

**Additional context**
The game still launches.

**Comment by DarkMatterCore** [comment]
@melsbacksfriend Hi there. Sorry for the long delay.

Seems like this could be related to #70. Same question, have you tried running the latest Lockpick_RCM release?

**Comment by wurffl** [comment]
Having the same problem, used the latest Lockpick_RCM release.

**Comment by DarkMatterCore** [comment]
@melsbacksfriend @wurffl Please redownload the NRO from the latest release page in this repository and report back, if possible.

**Comment by CynthiaFur** [comment]
I'm having the same problem also; using the latest release of Lockpick_RCM and the latest release of nxdumptool.

**Comment by DarkMatterCore** [comment]
@CynthiaFur Could you please share a screenshot of the problem?

**Comment by CynthiaFur** [comment]
I solved the issue by re-downloading nxdumptool from the homebrew shop and running it in applet mode. I just finished dumping the game a few minutes ago.

**Comment by DarkMatterCore** [comment]
@CynthiaFur Does the build date at the top match November 10th, 2020?

**Comment by CynthiaFur** [comment]
It doesn't. It says NXDumpTool v1.1.12. Built on Sep 26 2020

**Comment by DarkMatterCore** [comment]
@CynthiaFur Then it's an outdated build. I suggest you manually update the application by redownloading the NRO from the releases page in this repository - there was a silent update last month.

Please retry what you did under the latest build. If it works, I'll close this issue.

**Comment by CynthiaFur** [comment]
That's exactly what I did before I re-installed from the homebrew store and it didn't work. I could try it again, but I don't need to dump my game anymore

**Comment by DarkMatterCore** [comment]
> That's exactly what I did before I re-installed from the homebrew store and it didn't work. I could try it again, but I don't need to dump my game anymore

I'd greatly appreciate it, since I can't test it on my own. Please use this build whenever you get to it.

[nxdumptool.zip](https://github.com/DarkMatterCore/nxdumptool/files/5722213/nxdumptool.zip)

**Comment by ColonelThirtyTwo** [comment]
> Not worthy of bumping the version number.

> there was a silent update last month.

Please don't do this. It makes it very confusing when there are two versions with the same version number, as you have just witnessed. It's not like version numbers are scarce.

In any case, I ran into this issue with Pokemon Sword. The 1.1.12 built in sept 2020 didn't work, but the 1.1.12 built in nov 2020 did.

**Comment by DarkMatterCore** [comment]
@ColonelThirtyTwo Thanks for confirming the November build works.

The NRO from the release page was completely replaced, anyway. And forced updates can be performed from the application itself. The real issue here is when people redistribute the NRO when there's no need to do so - please don't do that.

**Comment by Trelior** [comment]
Sorry for the nearly two-month necrobump, but I am at a loss about dumping 1.3.1 Sword, as well. I thought that updating the dump tool was what I needed, but it clearly wasn't. It will get to this point, then roll over and die. What am I doing wrong?

![Snapshot_20210228_222227](https://user-images.githubusercontent.com/79821178/109448654-75d8a900-7a14-11eb-9787-f771558885ff.jpg)

**Comment by DarkMatterCore** [comment]
@Trelior Hi there, mate. It's okay, I was waiting for anyone other than me to comment on this issue.

Please provide more info about your current setup, or feel free to open a new issue (this is clearly not the same problem reported here).

**Comment by DarkMatterCore** [comment]
Closing this particular issue since it seems to have been resolved.
