### ISSUE TITLE
Can't Dump BOTW

### ISSUE THREAD

**Issue by ChaosCzar** [DarkMatterCore/nxdumptool#69]
**Describe the bug**
Unable to dump BOTW, tool is unable to find the file in the secure partition.

**To Reproduce**
1) Boot into CFW
2) Launch nxdumptool
3) Navigate to RomFS
4) Activate data dump

**Please fill the following information:**
- Horizon OS (Switch FW) version: 10.0.2
- CFW: Atmosphère
- CFW version: 0.15.0
- Atmosphère launch method (if applicable): Hekate
- NXDumpTool version: 1.1.12
- Homebrew launch method: Title Override
- Source storage used with the application (if applicable): Gamecard
- SD card specs: Sandisk Ultra 64 GB, FAT32 partition

**Screenshots**
![20201029_115603](https://user-images.githubusercontent.com/73660225/97605159-b253b400-19e4-11eb-937a-6289efdda7e8.jpg)

**Additional context**
Able to dump DLC, but unable to dump main game files.

**Comment by parkerlreed** [comment]
Hop by the Discord. There's a fixed build

**Comment by MrSuperNuts** [comment]
I'm having the exact same error, did you find out how to fix it?

**Comment by ChaosCzar** [comment]
> 
> 
> I'm having the exact same error, did you find out how to fix it?

Joined the Discord in the main post, there's some beta builds there!
