### ISSUE TITLE
Unable to dump RomFS DLC data or ExeFS update data for Pokemon Sword

### ISSUE THREAD

**Issue by Victini494** [DarkMatterCore/nxdumptool#70]
**Describe the bug**

When I try to dump data for the Crown Tundra DLC so I can randomize it, I receive the error

**To Reproduce**
1. Go to 'Dump gamecard content'
2. Go to either RomFS or Exefs Options
3. Scroll down to Use update/DLC and scroll right until you cannot anymore on both the RomFS or EexFS options
4. Select RomFS section data dump
5. See error "parseRomfsEntryFromNca: invalid header size for NCA RomFS section! (0x04454B21982C94F1 at 0x0000000000018000)

**Please fill the following information:**
- Horizon OS (Switch FW) version: 10.0.2
- CFW: Atmosphère
- CFW version: 0.14.4
- Atmosphère launch method (if applicable): Tried on both Hekate and fusee-primary
- NXDumpTool version: 1.1.12
- Homebrew launch method: not sure
- Source storage used with the application (if applicable): gamecard
- SD card specs: Sandisk 64 GB, FAT32 partition

**Screenshots**
Add screenshots to help explain your problem.
![Helpmepls](https://user-images.githubusercontent.com/73936292/98097269-670d2b80-1e52-11eb-9dff-00167d44c5e9.jpg)

**Additional context**
Base game RomFS and ExeFS dumps fine and game launches. Seems similar to an issue posted recently.
I'm very new to this so sorry if I posted improperly.

**Comment by DarkMatterCore** [comment]
@Victini494 Hi there. Sorry for the delay.

Have you tried running the latest Lockpick_RCM release?

**Comment by Imuswitch** [comment]
I know this issue is pretty old but I'm getting the same message when trying to dump Fire Emblem Three Houses. I have everything including the Lockpick_RCM and NXDumpTool on it's latest versions.
![20210322_184241](https://user-images.githubusercontent.com/81196283/112067529-93de8880-8b3e-11eb-9836-430549bd73ed.jpg)

**Comment by DarkMatterCore** [comment]
@Imuswitch Are you using a Mariko unit?

**Comment by Imuswitch** [comment]
No as far as I'm aware. I have a pretty old switch and all the other modding and homebrew stuff I've done in the past has worked.

**Comment by DarkMatterCore** [comment]
Please refer to https://github.com/DarkMatterCore/nxdumptool/issues/104#issuecomment-1175102727. This is probably related to bad cryptographic data handling in the `main` branch, though. I'll close this issue.
