### ISSUE TITLE
Not able to dump/browse romfs from gamecard

### ISSUE THREAD

**Issue by cucholix** [DarkMatterCore/nxdumptool#71]
**Bug description:**
nxdumptool is not able to dump/browse romfs partition on gamecards.

**To Reproduce:**
1. Insert whatever gamecard on gamecard slot
2. Navigate to nxdumptool app and open
3. Select "Dump gamecard content"
4. Select "RomFS options" 
5. Select either "RomFS section data dump" or "Browse RomFS section"
6. You will get this error screen:

![photo_2020-11-06_07-03-23](https://user-images.githubusercontent.com/16081693/98442163-dcdaf680-20e1-11eb-9f26-03cafd1c3f7b.jpg)

**System information:**
- Horizon OS (Switch FW) version: 10.2.0
- CFW Atmosphère: AMS 0.15.0|S
- Atmosphère launch method (if applicable): fusee-primary
- NXDumpTool version: 1.1.12 (hotfix included)
- Homebrew launch method: title override
- Source storage used with the application (if applicable): gamecard
- SD card specs: SanDisk Extreme 1TB, FAT32 partition

**Additional information:**
RomFS dump/browse works just fine with digital downloaded games, you can dump/browse exeFS partition on gamecards too but no RomFS. I suspect updating atmosphere was the culprit since no other big change has been made on my end, it used to work fine.

**Comment by parkerlreed** [comment]
Check out the Discord server. There's some fixed builds there.

**Comment by LyuboA31** [comment]
> Check out the Discord server. There's some fixed builds there.

what discord server

**Comment by DarkMatterCore** [comment]
Fixed in c471e61aff8c9e9d9cba2d9d213197b283835a8e.

And yes, it's a problem triggered by AMS 0.15.0.
