### ISSUE TITLE
Can only dump into XCI format

### ISSUE THREAD

**Issue by thunder919113** [DarkMatterCore/nxdumptool#72]
**Describe the bug**
When trying to dump a physical game into any avaliable format besides xci i get the error message "readFileFromSecureHfs0PartitionByName: unable to find file "/00521af773b9012a1fd434e7375482d8.nca" in Secure HFS0 partition!
readNcaDataByContentId: failed to read 3072 bytes block offset 0x00000000000000000 from NCA "00521af773b9012a1fd434e7375482d8"! (0x00000000)
readNcaRomFsSection: failed to read header from Program NCA!"
**To Reproduce**
1. Go to Dump gamecard content
2. Click on RomFS options
3. Make sure settings are "split files bigger than 4 gb = yes,
Save data to cfw directory = no,
Use update/DLC yes"
4. Select RomFS data dump
5. Error

**Please fill the following information:**
- Horizon OS (Switch FW) version: 11.0.0
- CFW: Atmosphere
- CFW version: 0.16.0
- Atmosphère launch method (if applicable): Hekate
- NXDumpTool version: v1.1.12
- Homebrew launch method: title override
- Source storage used with the application (if applicable): gamecard
- SD card specs: Gigastone 128GB SD card FAT32 format

**Screenshots**
Add screenshots to help explain your problem.
![16071215596804093455526044112676](https://user-images.githubusercontent.com/75506104/101222404-51f10b80-364f-11eb-820f-69fd7cc9d891.jpg)

**Additional context**
I was trying to dump The Legend of Zelda: Breath of The Wild, I attempted it with Kirby: Star Alies Atwell and the bug was consistent

**Comment by DarkMatterCore** [comment]
You're using an old build. Please redownload the NRO from the latest release page in this repository.

**Comment by thunder919113** [comment]
The latest version on github (for me at least) is ver 1.1.12, the version im using. Can you send me a link to the latest version?

**Comment by thunder919113** [comment]
> You're using an old build. Please redownload the NRO from the latest release page in this repository.
I'm using version 1.1.12, unless I'm mistaken thats the latest version on girhub

**Comment by DarkMatterCore** [comment]
The version number is the same, but the build date isn't (compare the first line at the top while running the application). I can guarantee it's a different NRO.

**Comment by thunder919113** [comment]
The date is the same. Sep 26 2020 08:51:29

**Comment by thunder919113** [comment]
Oh wait the hour is different sorry, ill re-download straight away
