### ISSUE TITLE
App fails to dump RomFS data from updates

### ISSUE THREAD

**Issue by MegAmi24** [DarkMatterCore/nxdumptool#74]
**Describe the bug**
Whenever attempting to dump RomFS files contained in an update for a game, the following error occurs:
"readBktrSectionBlock: BKTR references non-existent base RomFS section!"
The user is then given the option of whether or not they want to delete any files they've dumped prior to the error occurring.
Content from the base game or DLC dumps without issues.

**To Reproduce**
1. Select a game with update data
2. Go to "RomFS options" and under "Use update/DLC:", choose an update
3. Go to "Browse RomFS section" and browse the file explorer until you find a file from the update
4. Press A to (attempt to) dump it

**Please fill the following information:**
- Horizon OS (Switch FW) version: 11.0.1
- CFW: Atmosphère
- CFW version: 0.16.2
- Atmosphère launch method (if applicable): Hekate v5.5.1
- NXDumpTool version: v1.1.12
- Homebrew launch method: title override
- Source storage used with the application (if applicable): gamecard, SD and eMMC all have this issue
- SD card specs: SanDisk 128 GB, FAT32 partition

**Screenshots**

**Additional context**
I have run the latest version of Lockpick_RCM prior to this issue occurring.

**Comment by DarkMatterCore** [comment]
Just redownload the latest NRO. There was a silent update last month.
