### ISSUE TITLE
Dump of Pokemon Sword v1.3.1 Fails Inexplicably at 92%

### ISSUE THREAD

**Issue by Trelior** [DarkMatterCore/nxdumptool#77]
**Describe the bug**
As stated in the title, everything goes smooth sailing until it his stream.pck, then it fails to write.

**To Reproduce**

1. Go to dump installed sd card emmc content
2. Click on Pokémon Sword
3. Choose romfs options
4. Use the update
5. Choose romfs section data dump

**Please fill the following information:**
- Horizon OS (Switch FW) version: 11.0.1
- CFW: Atmosphère
- CFW version: 17.0
- Atmosphère launch method (if applicable): Hekate v5.5.1
- NXDumpTool version: 1.1.13
- Homebrew launch method: title override
- Source storage used with the application (if applicable): SD
- SD card specs: Onn 256 GB microSD, FAT32

**Screenshots**
![Snapshot_20210228_222227](https://user-images.githubusercontent.com/79821178/109450442-e1247a00-7a18-11eb-941f-004f31a37814.jpg)

**Additional context**
Instructed to open as a new bug report. I have no idea what I've done wrong. Game will launch and play no problem.

Not sure if this is relevant, but the write speed tanks from 6.5-7.2 MB/s to the 4.25 shown at around 91%, particularly at the language pack section of the dump.

**Comment by Trelior** [comment]
I may have discovered what the issue was. Either the disk is smaller than advertised or there's some jank with block size. I attempted to dump the ROM by individual directories, and it just ran out of space at romfs:/bin/Script_Event_Data, leaving no room for ./Sound

Seems the issue was entirely at the fault of my own hardware. Sorry for wasting you time, sir.

**Comment by Sperguze** [comment]
I'm having the same problem with the same ammount of free space on the sd card. Do you think it'll be fixed by uninstalling some things before dumping?

**Comment by Trelior** [comment]
That's what I ended up doing. I deleted a game that I had backed up that does me no good to have a second copy. Then I migrated my eMMC backup to dump Shield afterward.

**Comment by Sperguze** [comment]
That seemed to be the problem, thanks.
