### ISSUE TITLE
Issue Initiating Game Dump

### ISSUE THREAD

**Issue by TheJoshuaRusso** [DarkMatterCore/nxdumptool#83]
I have the prod.keys in SD:/Switch/Prod.keys and every time I attempt to dump a game I get an error saying "decryptNcaHeader: invalid NCA magic word! Wrong header key? (0x1BDCDBD9)
Try running lockpick_RCM to generate the keys from scratch. (Which I did)
![2021041123414300-B8FAEF4816CAC2B76D11869B05CA7601](https://user-images.githubusercontent.com/82071714/114351784-ef89a980-9b1f-11eb-92cd-dfb87c8c77ff.jpg)

**Please fill the following information:**
- Firmware 12.0.0
- CFW: Atmosphere
- CFW version: 0.19.0
- Atmosphère launch method: fusee-primary
- NXDumpTool version: 1.1.13
- Homebrew launch method: title override
- Source storage used with the application (if applicable): SD/eMMC
- SD card specs: SanDiskUltra 128GB, FAT32

**Screenshots**

**Comment by DarkMatterCore** [comment]
HOS 12.0.0 isn't properly supported at this moment. libnx hasn't been updated, and some ams_libs are currently broken. Please use a lower firmware version (or alternatively, nxdumptool v1.1.12) and try again.

**Comment by TheJoshuaRusso** [comment]
> HOS 12.0.0 isn't properly supported at this moment. libnx hasn't been updated, and some ams_libs are currently broken. Please use a lower firmware version (or alternatively, nxdumptool v1.1.12) and try again.

That worked! Thank you so much!

**Comment by DarkMatterCore** [comment]
Fixed in b1fa56d4784cfa4bd3524b65acac44336964ea99.
