### ISSUE TITLE
Failed to initialize socket

### ISSUE THREAD

**Issue by manselmi** [DarkMatterCore/nxdumptool#84]
**Describe the bug**
Getting "failed to initialize socket" error message.

**To Reproduce**
1. Launch nxdumptool
1. Select `Update options`
1. Select `Update NSWDB.com XML database`
1. Observe error message colored red: `updateNSWDBXml: failed to initialize socket! (0000F601)`

(Similar error message if `Update application` selected instead: `updateApplication: failed to initialize socket! (0000F601)`)

**Please fill the following information:**
- Horizon OS (Switch FW) version: 12.0.0
- CFW: Atmosphère
- CFW version: 0.19.1
- Atmosphère launch method (if applicable): [fusee-primary](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.19.1) via Hekate 5.5.5
- NXDumpTool version: 1.1.13
- Homebrew launch method: hold R while launching a game to launch Homebrew menu (not sure what this launch method is called)
- Source storage used with the application (if applicable): SD/emuMMC
- SD card specs: SanDisk SC400 400GB, FAT32 partition

**Screenshots**
None attached as error message is simple enough.

**Additional context**
This worked fine with Horizon OS 11.0.1 and Atmosphère 0.18.1, so perhaps there's some incompatibility between nxdumptool 1.1.13 and one of those.  Also, confirmed that Wifi is working by launching the Homebrew App Store and browsing around.

Finally, thanks so much for maintaining nxdumptool!  ❤️

**Comment by DarkMatterCore** [comment]
Hi there, mate. It's a pleasure to meet you.

Please try using nxdumptool v1.1.12. v1.1.13 introduced a dependency on Atmosphère `sm` extensions, which are currently broken in AMS 0.19.x.

**Comment by manselmi** [comment]
Thanks @DarkMatterCore, v1.1.12 is indeed working well.

I'm not sure if you would like this issue kept open as a signpost to others, so I'll leave it as-is, but please do whatever you like with this issue.

**Comment by DarkMatterCore** [comment]
@manselmi Don't worry, I'll keep it open for the time being. There's not much I can do beyond waiting at this moment.

**Comment by 13xforever** [comment]
I don't see any specific issue filed against this issue in ams repo, and release notes explicitly mention the need to recompile against new version of libnx to support new changes brought with 12.0/ams 0.19

**Comment by DarkMatterCore** [comment]
Fixed in b1fa56d4784cfa4bd3524b65acac44336964ea99.
