### ISSUE TITLE
Unable to dump cart with atmosphere for 12.0.0

### ISSUE THREAD

**Issue by NicholasIstr** [DarkMatterCore/nxdumptool#85]
**Describe the bug**
not dumping loadmemorykeys failed to initialize the spl:crypto service

**To Reproduce**
Try and dump a cart with latest Atmosphere 0.19.1

**Please fill the following information:**
- Horizon OS 12.0.0
- CFW: Atmosphere
- CFW version: 0.19.1
- Atmosphère launch method : Heckate
- NXDumpTool version: 1.1.13
- Homebrew launch method: title override
- Source storage used with the application : sdcard
- SD card specs: onn 256gb exfat

**Comment by Masamune3210** [comment]
try using 1.1.12

**Comment by NicholasIstr** [comment]
That worked. Thanks a ton

**Comment by racer-face** [comment]
I had the same problem and AMS/HOS version as OP and I can confirm that replacing the 1.1.13 .nro file with the 1.1.12 .nro file in the sdmc:/switch/nxdumptool/ directory worked for me.
