### ISSUE TITLE
Won't dump RomFS or ExeFS for SD card to Gamecard games

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [DarkMatterCore/nxdumptool#86]
**Describe the bug**
Won't dump RomFS or ExeFS for SD card to Gamecard games

**To Reproduce**
1. Get key's using LockpickRCM and TegraRCM_GUI
2. Launch into CFW
3. Hold R while loading game to bring up the HB menu (This case it's Pokemon Sowrd)
4. Go to NxDumpTool
5. Click gamecard content
6. Use RomFS for ExeFS
7. Don't split into 4 parts, use LayerdFS, used updated version
8. Try to dump
9. Won't work

**Please fill the following information:**
- CFW: Atmosphere
- CFW version: Latest
- Atmosphère launch method (if applicable): Hekate: Fusee_Primary.bin
- NXDumpTool version: Latest
- Homebrew launch method: [e.g. title override, applet]
- Source storage used with the application (if applicable): Gamecard and SD
- SD card specs: 512GB FAT32 format

**Screenshots**
![My Great Capture Screenshot 2021-04-12 18-22-37](https://user-images.githubusercontent.com/79018578/115123554-9b515000-9f8b-11eb-82db-ca19a0a95ce5.png)
![My Great Capture Screenshot 2021-04-12 18-23-42](https://user-images.githubusercontent.com/79018578/115123555-9b515000-9f8b-11eb-84ed-d6207c435fe2.png)

**Comment by Pixelplayz2215YT** [comment]
It says to get the keys but I already have them

**Comment by Masamune3210** [comment]
Use previous version or wait for a update, latest atmos and HOS changed internal things and a update for this has to be released to take those changes into account

**Comment by Pixelplayz2215YT** [comment]
> Use previous version or wait for a update, latest atmos and HOS changed internal things and a update for this has to be released to take those changes into account

I tried to use a previous version, but when I launch it in my switch Atmosphere crashes and I have to reload my Payload to get back to CFW

**Comment by Pixelplayz2215YT** [comment]
This always happens when I launch an earlier version

![My Great Capture Screenshot 2021-04-18 16-31-51](https://user-images.githubusercontent.com/79018578/115159934-b42d3480-a063-11eb-8b1c-d53f10f7f3e6.png)
![My Great Capture Screenshot 2021-04-18 16-32-11](https://user-images.githubusercontent.com/79018578/115159935-b42d3480-a063-11eb-80ca-65bf1b44fe45.png)

**Comment by DarkMatterCore** [comment]
@Pixelplayz2215YT That looks like a corrupted NRO. If you're using FTP to transfer the NRO from an older release, consider using a MTP responder homebrew or Hekate's UMS feature instead.

**Comment by Pixelplayz2215YT** [comment]
I turn off my switch and put the SD card into my pc and do it that way, then I go to drive tools and click Eject to avoid corruption.

**Comment by DarkMatterCore** [comment]
@Pixelplayz2215YT Then redownload the NRO. The nxdumptool icon should be displayed in the Homebrew Menu before launching it.

**Comment by Pixelplayz2215YT** [comment]
I re-downloaded it 5 times now, same thing, should I wait for the next NxDumptool update?

**Comment by Masamune3210** [comment]
Maybe sd filesystem issues? Try backing up your card and reformatting it as fat32

**Comment by Pixelplayz2215YT** [comment]
> Maybe sd filesystem issues? Try backing up your card and reformatting it as fat32

I can try that, but I don't have my computer rn, it's being worked on as my GPU is fried, I am working on getting a replacement. So it might be a while untill I give you an answer on if it worked or not

**Comment by Masamune3210** [comment]
you could try to move/uninstall all the games from your sd card and clean out your sd card of anything you don't need, then use hekate's formatter. If you have a low enough amount of stuff stored on your card it will preserve them for you

**Comment by DarkMatterCore** [comment]
Fixed in b1fa56d4784cfa4bd3524b65acac44336964ea99.
