### ISSUE TITLE
Broke on 12.0.0

### ISSUE THREAD

**Issue by fennectech** [DarkMatterCore/nxdumptool#87]
Dumping no longer works.  Its also unable to retreve the games name.

**Comment by Whovian9369** [comment]
Which version of the app did you use?

**Comment by fennectech** [comment]
1.1.13

**Comment by Whovian9369** [comment]
Update to https://github.com/DarkMatterCore/nxdumptool/releases/tag/v1.1.14

**Comment by fennectech** [comment]
Am stupid.   1.1.14 is live
