### ISSUE TITLE
some long title games like 4 in 1 cartridge game dump failed.

### ISSUE THREAD

**Issue by guiviewer** [DarkMatterCore/nxdumptool#88]
Describe the bug
cartridge game dump failed since the filename is too long.

To Reproduce
1. Go to dump cartridge game.
2. Game title 'Honkaku AI Tosai Table Games: Texas Holdem Poker, Mahjong, Chess, Daifugo'
3. See error dumpNXCardImage: failed to open output file "sdmc://switch/nxdumptool/XCI/(long file name).xci

Please fill the following information:

Horizon OS (Switch FW) version: 12.0.2
CFW: Atmosphère
CFW version: 0.19.3
Atmosphère launch method (if applicable): Hekate v5.5.6
NXDumpTool version: 1.1.14
Source storage used with the application (if applicable): SD
SD card specs: 256 GB microSD, exFat

**Comment by DarkMatterCore** [comment]
@guiviewer Hi there, mate. Thanks for reporting this issue.

Please hit me up via Discord in order to better assist you to overcome this issue. My Discord handle is `DarkMatterCore#4814`.

**Comment by toxicated101** [comment]
What was the resolution on this as I have got the same issue with  nxdumptool 1.1.15. Trying to dump a long path / file name
