### ISSUE TITLE
Super Mario Odyssey save wiped from cart

### ISSUE THREAD

**Issue by Mewthree3** [DarkMatterCore/nxdumptool#89]
**Describe the bug**
The save from my little brother's SMO cart got wiped when I dumped the NSP to my console.

**To Reproduce**
Dump a cart to NSP, with Fat32 storage ON.

**Please fill the following information:**
- Horizon OS 12.0.2 (latest)
- CFW: Atmosphere 0.19.3
- Atmosphère launch method (if applicable): Hekate
- NXDumpTool version: Version bundles with sdsetup.com
- Homebrew launch method: Standalone homebrew launcher NSP
- Source storage used with the application (if applicable): Gamecard
- SD card specs: Sandisc 200GB, L4T, Switchdroid, 5GB emummc (I don't use it), and Fat32 partitions

**Comment by DarkMatterCore** [comment]
Savegames are *not* stored on gamecards, but rather on the internal eMMC storage from the Switch. Use [Checkpoint](https://github.com/FlagBrew/Checkpoint) or [JKSV](https://github.com/J-D-K/JKSV) to manually transfer savedata from one console to another.
