### ISSUE TITLE
Compatibility with PegaSwitch on FW < 4.0.0.

### ISSUE THREAD

**Issue by DarkMatterCore** [DarkMatterCore/nxdumptool#9]
Since CFWs (Hekate, SX OS) provide full permissions under FW >= 4.0.0, the application works fine while using them. However, lower firmware versions are also compatible with PegaSwitch, which is launched at runtime once the system has already booted and thus, doesn't offer the same access permissions.

There's a [dumpXCI.js PegaSwitch script](https://gist.github.com/AcK77/56b86469faef238157a0e02cb962ee30) made by @AcK77 that works by performing a privilege escalation procedure to gain access to FS services. I have tried to port that code to libnx in order to make the application able to perform such procedure as well, but it hasn't worked for me.

Any help/hints on this matter would be greatly appreciated.

**Comment by mafischer** [comment]
@DarkMatterCore, I'm not sure if you've seen it, but here's a technical writeup that may give you the hints your looking for:

http://hexkyz.blogspot.com/2018/12/the-switch-memoir.html

**Comment by DarkMatterCore** [comment]
@mafischer 

Hi there. Sorry for taking so long to answer, a lot of things have happened in my personal life in the past few months, and they have kept me busy enough to stop browsing the Internet as much as I'd like.

Even though I did read the technical writeup you provided, I must admit that sadly, some of the stuff hexkyz suggests over theme are beyond my capabilities. Nonetheless, I truly appreciate the help.

This issue will be kept open, hoping that at some we reach compatibility with PegaSwitch.

**Comment by DarkMatterCore** [comment]
Since PegaScape has pretty much become mainstream at this point, I don't believe it will be necessary to fix this. Just use it to reboot the console into a full fledged CFW if you wish to use the application.
