### ISSUE TITLE
DAEMON X MACHINA, Yoshi's Crafted World, and Starlink - Battle for Atlas : Update Dump Error

### ISSUE THREAD

**Issue by monokuma9** [DarkMatterCore/nxdumptool#90]
**Describe the bug**
Hello,

I've downloaded nxdumptool from sdmaker's website (and updated through the homebrew launcher) as per Nintendo Switch Homebrew guidelines and I've been able to dump most of the titles and updates I've tried. There are just a couple of updates that just won't dump that I can find no suggestions on. That being that attempts at dumping updates for DAEMON X MACHINA, Yoshi's Crafted World, or Starlink - Battle for Atlas obtained from cartridge versions all fail. No other updates or games fail including some updates larger than two of these.

**To Reproduce**
1. Go to nxdumptool from the homebrew menu in SysMMC from Hekate using a model 1 switch using a Jig
2. Click on "Dump Installed SD card/ eMMC content"
3. press the Y button to dump installed applications with missing bare applications
4. Scroll down to the update for DAEMON X MACHINA, Yoshi's Crafted World, or Starlink - Battle for Atlas
5. Click "Nintendo Submission Package (NSP) Dump"
6. See Error

**Please fill the following information:**
- Horizon OS (Switch FW) version: 12.0.3
- CFW: Atmosphere
- CFW version: 5.5.6
- Atmosphère launch method (if applicable): Hekate
- NXDumpTool version: 1.1.14
- Homebrew launch method: 
- Source storage used with the application (if applicable): Gamecard, but the title I'm dumping is in SD/MMC
- SD card specs: SanDisk - Ultra PLUS 256GB microSDXC UHS-I Memory Card - FAT32

**Screenshots**
DAEMON X MACHINA: 
![2021061112374400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/54414913/121721158-eed6aa80-cab1-11eb-9728-75c306174591.jpg)
Yoshi's Crafted World:
![2021061112381200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/54414913/121721114-e3837f00-cab1-11eb-8f8a-1f96026346b8.jpg)
Starlink - Battle for Atlas: 
![2021061112380000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/54414913/121721152-ed0ce700-cab1-11eb-8c2e-c54a3a509496.jpg)

**Additional context**
This happens with any and all settings ticked in the dump process that I've tried. I've found no noticeable difference between any of them.

Thank you!

**Comment by DarkMatterCore** [comment]
Run the application in title override mode (press R while launching a game). Applet mode offers ~300 MiB, which is not enough to decompress the full NSO from certain games.

This is exactly why the application displays a warning if it's launched using applet mode.
