### ISSUE TITLE
Allow dumping all DLC for a game at once

### ISSUE THREAD

**Issue by martmists-gh** [DarkMatterCore/nxdumptool#93]
**Is your feature request related to a problem? Please describe.**
For some games (like Smash) you need to dump about 13 DLC files. In most cases, you'd want to dump all DLC anyway, so adding a shortcut to dump all would be useful.

**Describe the solution you'd like**
Add an option to dump all DLC (Yes/No option). When enabled, the picker for which DLC to dump greys out and is ignored.

**Describe alternatives you've considered**
Dumping one by one does work but it would be nicer to have them all dumped automatically.

**Comment by DarkMatterCore** [comment]
Press Y on the SD/eMMC submenu. It'll open a batch dump menu.
