### ISSUE TITLE
Dumped e-Shop titles try to phone home - "Checking whether this software can be played..."

### ISSUE THREAD

**Issue by alexgleason** [DarkMatterCore/nxdumptool#94]
**Describe the bug**
e-Shop titles dumped as NSPs with nxdumptool cannot be played offline. They attempt to connect to the internet, getting stuck forever.

**To Reproduce**
1. Dump an e-Shop title as an NSP with nxdumptool. Enable "remove console-specific data" and "ticketless dump" options.
2. Import the NSP on another partition and attempt to launch it.

**Please fill the following information:**
- Horizon OS (Switch FW) version: 12.0.3
- CFW: Atmosphère
- CFW version: 12.0.3|AMS M.19.5|E
- Atmosphère launch method (if applicable): Hekate
- NXDumpTool version: 2.4.1
- Homebrew launch method: override
- Source storage used with the application (if applicable): SD
- SD card specs: Samsung EVO 512 GB, FAT32 partition

**Screenshots**
![2021072123120400-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/3639540/126589121-090f5c64-521d-4130-b2fd-4f08fd35e1c7.jpg)

**Additional context**
This is probably not a bug in nxdumptool, but rather just an aspect of e-Shop titles. I don't know if it's possible for nxdumptool to detect and remove this check. But if it can, it should.

Physical carts dumped with nxdumptool work just fine, it's only e-Shop titles I've dumped myself that are a problem. NSPs I've downloaded from the internet also work just fine. I have the latest sigpatches.

**Comment by DarkMatterCore** [comment]
> NSPs I've downloaded from the internet also work just fine.
Sorry, we don't support piracy.

**Comment by alexgleason** [comment]
I was referring to homebrew NSPs, but okay. Thanks for ignoring the rest of my issue except that one line and being rude about it.

**Comment by Masamune3210** [comment]
Not rude, just stating the fact. Not supported means no more support. NSP means sigpatches, sigpatches are piracy tools
