### ISSUE TITLE
Broken on 12.1.0

### ISSUE THREAD

**Issue by fennectech** [DarkMatterCore/nxdumptool#95]
1.1.14 is broken.  Its unable to get debug handle for 0100000000000 and none of the games versions show.

**Comment by DarkMatterCore** [comment]
@fennectech Please provide more information about your setup. I can barely do anything with that info.

**Comment by fennectech** [comment]
Its just 12.1.0 with a few few sysmodules.  Ive no real changes to the firmware.    Does it work on 12.1.0 on your end?   What specifics would you like.  But i am running the latest deepsea with the latest atmosphere.

**Comment by fennectech** [comment]
Hekate.

**Comment by fennectech** [comment]
I see.   I deleted the forwarders i had installed and that fixed it.   It was running under a forwarder.  I will gather more information (and provide the forwarder creator i use)

**Comment by DarkMatterCore** [comment]
It's an issue in the forwarder creator you're using, then. There's nothing to fix in nxdumptool.

**Comment by fennectech** [comment]
Would you be willing to help me troubleshoot the issue so i can make a suggestion to the ones who create this forwarder maker?

**Comment by DarkMatterCore** [comment]
@fennectech Sure, hit me up via Discord.
