### ISSUE TITLE
Main.npdm file is missing even though its there

### ISSUE THREAD

**Issue by Inferno08642** [DarkMatterCore/nxdumptool#96]
I'm trying to randomize my pokemon sword but an error message keeps popping up.
failed to open -- E:\switch\nxdumptool\RomFS\pok__mon sword v0 (0100ABF008968000) (BASE)

could not find file 'E:\switch\nxdumptool\RomFS\pok__mon sword v0 (0100ABF008968000) (BASE)\exefs\main.npdm'.

But my main.npdm file is there and I don't know why it says it isn't. 
How do I fix this issue.

**Comment by DarkMatterCore** [comment]
This is unrelated to nxdumptool itself, even more so considering you've already dumped the game's ExeFS section (which is where the main.npdm file is stored).

Please seek help in the repository from the tool you're using.
