### ISSUE TITLE
parseRomFsEntryFromNca & readNcaDataByContentId on some new games.

### ISSUE THREAD

**Issue by Slluxx** [DarkMatterCore/nxdumptool#97]
**Describe the bug**
Some new games (like Lost in Random) have some sort of new structure which makes it impossible for nxdumptool to dump the NSP & Browse RomFS or ExeFS.

**To Reproduce**
Install Lost in Random (eshop or tinfoil, the others do not seem to work) and try to do anything with the game.

**Please fill the following information:**
- Horizon OS (Switch FW) version: 13.0.0
- CFW: Atmosphere
- CFW version: 1.0.0
- Atmosphère launch method (if applicable): Hekate, fss0
- NXDumpTool version: 1.1.14
- Homebrew launch method: Title override
- Source storage used with the application (if applicable): emmc
- SD card specs: Fat32 512gb samsung something

**Screenshots**
no

**Additional context**
no

**Comment by illyasever-lol** [comment]
No mo hero eshop and Fuuraiki 4 also like this.
Now i use dbi mtp modle to dump game.
U can go installed saw all game,and copy it to u computer.
U can use dbi or tinfoil to install like this game.

**Comment by Whovian9369** [comment]
Note that using apps like Tinfoil WILL get your console banned.

**Comment by Masamune3210** [comment]
Kind of a moot point, installing nsp's or pretty much anything you don't have a legit ticket for will get you banned, not just that numpty of a app

**Comment by Slluxx** [comment]
Why is so much offtopic talk here? Thats not what github is for.

**Comment by DarkMatterCore** [comment]
Please refer to https://github.com/DarkMatterCore/nxdumptool/issues/104#issuecomment-1175102727. I'll close this issue.
